import assert from 'node:assert/strict';
import {registerHooks} from 'node:module';
import {JSDOM} from 'jsdom';
import React,{act,useState} from 'react';
registerHooks({load(url,ctx,next){if(url.endsWith('.css'))return{format:'module',source:'export default {}',shortCircuit:true};return next(url,ctx);}});
const dom=new JSDOM('<html><body><div id="root"></div></body></html>',{url:'http://localhost',pretendToBeVisual:true});
for(const key of ['window','document','navigator','HTMLElement','Element','Node','MutationObserver','localStorage','sessionStorage','Event','MouseEvent','CustomEvent','HTMLInputElement'])Object.defineProperty(globalThis,key,{configurable:true,value:(dom.window as any)[key]});
Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});
const {storage,setStoredData}=await import('../services/storage');
storage.getCurrentUser=()=>({id:'qa',role:'admin',status:'active',name:'اختبار'} as any);
storage.getUiState=(_key:any,fallback:any)=>fallback;
storage.saveUiState=()=>{};
const {CurriculumTreeView}=await import('../modules/curriculum/pages/CurriculumTreeView');
const {createRoot}=await import('react-dom/client');
const fixtures:any[]=[{id:'b',name:'فيزياء',code:'PHYS',description:'مادة اختبار',icon:'Atom'},{id:'a',name:'رياضيات',code:'MATH',icon:'Calculator'}];
const units:any[]=[{id:'u',subjectId:'a',title:'التفاضل'}];
const lessons:any[]=[{id:'l',subjectId:'a',unitId:'u',title:'درس اختبار'}];
const questions:any[]=[{id:'q',subjectId:'a',lessonId:'l',lessonIds:['l']},{id:'q',subjectId:'a',lessonId:'l'},{id:'q2',subjectId:'b'}];
let saved:any,deleted='',editorOpened=false,failSave=false;
function Harness({empty=false,loading=false,error=null}:{empty?:boolean;loading?:boolean;error?:string|null}){
const[subjects,setSubjects]=useState(empty?[]:fixtures);
return <CurriculumTreeView subjects={subjects} units={units} lessons={lessons} questions={questions} isLoading={loading} loadError={error} onRetry={()=>{deleted='retry';}} onSaveSubject={s=>{if(failSave)return false;saved=s;setSubjects(prev=>prev.some(p=>p.id===s.id)?prev.map(p=>p.id===s.id?s:p):[...prev,s]);return true;}} onDeleteSubject={id=>{deleted=id;setSubjects(prev=>prev.filter(p=>p.id!==id));}} onSaveUnit={()=>{}} onDeleteUnit={()=>{}} onSaveLesson={()=>{}} onDeleteLesson={()=>{}} onOpenLessonEditor={()=>{editorOpened=true;}}/>;
}
const root=createRoot(document.getElementById('root')!);
const settle=async(fn:()=>void)=>act(async()=>{fn();await new Promise(r=>setTimeout(r,15));});
const click=async(text:string)=>{const b=Array.from(document.querySelectorAll<HTMLElement>('button,summary')).find(e=>e.textContent?.trim()===text||e.getAttribute('aria-label')===text);assert.ok(b,text);await settle(()=>b.click());};
const input=async(el:HTMLInputElement,value:string)=>settle(()=>{Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype,'value')!.set!.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));});
const query=()=>document.querySelector<HTMLInputElement>('[aria-label="بحث باسم المادة أو رمزها"]')!;
await settle(()=>root.render(<Harness/>));
assert.deepEqual(Array.from(document.querySelectorAll('.cs-stats strong')).map(e=>e.textContent),['2','1','1','2']);
assert.equal(document.querySelectorAll('.cs-card').length,2);
await input(query(),'MATH');assert.equal(document.querySelectorAll('.cs-card').length,1);
assert.equal(document.querySelector('.cs-card h2')!.textContent,'رياضيات');
const scroll=document.querySelector('.overflow-y-auto') as HTMLElement;scroll.scrollTop=175;
await click('عرض الوحدات');assert.match(document.body.textContent!,/التفاضل/);assert.equal(editorOpened,false);
await click('المناهج');assert.equal(query().value,'MATH');assert.equal(scroll.scrollTop,175);
await input(query(),'');const sort=document.querySelector<HTMLSelectElement>('[aria-label="ترتيب المواد"]')!;
await settle(()=>{sort.value='name';sort.dispatchEvent(new Event('change',{bubbles:true}));});assert.equal(document.querySelector('.cs-card h2')!.textContent,'رياضيات');assert.equal(fixtures[0].id,'b');
await input(query(),'غير موجود');assert.match(document.body.textContent!,/لا توجد نتائج مطابقة/);await click('مسح البحث');
await click('إجراءات مادة رياضيات');assert.ok(document.querySelector('.cs-grid'));await click('تعديل المادة');await click('إلغاء');assert.equal(saved,undefined);
await click('إضافة مادة');await input(document.querySelector<HTMLInputElement>('input[placeholder^="مثال: الرياضيات"]')!,'كيمياء اختبار');
failSave=true;await click('إضافة المادة');assert.match(document.body.textContent!,/تعذر حفظ المادة/);assert.equal(saved,undefined);
failSave=false;await click('إضافة المادة');assert.equal(saved.name,'كيمياء اختبار');await click('المناهج');
await click('إجراءات مادة رياضيات');await click('تعديل المادة');await input(document.querySelector<HTMLInputElement>('input[placeholder^="مثال: الرياضيات"]')!,'رياضيات معدلة');await click('حفظ التعديلات');assert.equal(saved.id,'a');assert.equal(saved.name,'رياضيات معدلة');await click('المناهج');
await click('إجراءات مادة رياضيات معدلة');await click('حذف المادة');assert.match(document.body.textContent!,/تبقى الأسئلة في البنك/);assert.equal(deleted,'');await click('إلغاء');assert.equal(deleted,'');
await click('إجراءات مادة رياضيات معدلة');await click('حذف المادة');await click('نعم، تأكيد الحذف نهائياً');assert.equal(deleted,'a');assert.equal(document.querySelectorAll('.cs-card').length,2);
await settle(()=>root.render(<Harness key="empty" empty/>));assert.match(document.body.textContent!,/لا توجد مواد لعرضها/);await click('إضافة أول مادة');await click('إلغاء');
await settle(()=>root.render(<Harness key="loading" loading/>));assert.equal(document.querySelector('.cs-stats'),null);assert.match(document.body.textContent!,/جارٍ تحميل/);
await settle(()=>root.render(<Harness key="error" error="تعذر التحميل"/>));assert.equal(document.querySelector('.cs-stats'),null);await click('إعادة المحاولة');assert.equal(deleted,'retry');
await settle(()=>root.unmount());
console.log('PASS curriculum production UI: counts/dedup, search, sort, correct subject, return/scroll, add/edit/cancel/failure, delete confirmation, loading/error/empty');
// Exercise the unchanged storage deletion policy in isolated test storage only.
for(const [key,value] of Object.entries({edutech_subjects_v1:fixtures,edutech_units_v1:units,edutech_lessons_v1:lessons,edutech_lesson_cards_v1:{l:[{id:'card',lessonId:'l',content:'اختبار'}]},edutech_questions_v1:[questions[0],questions[2]]}))setStoredData(key,value);
storage.deleteSubject('a');
assert.deepEqual(storage.getSubjects().map(s=>s.id),['b']);
assert.equal(storage.getUnits().length,0);assert.equal(storage.getLessons().length,0);
const remaining=storage.getQuestions();assert.equal(remaining.length,2);assert.equal(remaining.find(q=>q.id==='q')!.subjectId,'');assert.equal(remaining.find(q=>q.id==='q2')!.subjectId,'b');
assert.equal(JSON.parse(localStorage.getItem('edutech_lesson_cards_v1')!).l,undefined);
console.log('PASS unchanged subject deletion policy: children removed, bank questions retained, unrelated subject intact');
