import assert from 'node:assert/strict';
import {registerHooks} from 'node:module';
import {JSDOM} from 'jsdom';
import React,{act,useState} from 'react';
registerHooks({load(url,ctx,next){if(url.endsWith('.css'))return{format:'module',source:'export default {}',shortCircuit:true};return next(url,ctx);}});
const dom=new JSDOM('<html><body><div id="root"></div></body></html>',{url:'http://localhost',pretendToBeVisual:true});
for(const key of ['window','document','navigator','HTMLElement','Element','Node','MutationObserver','localStorage','sessionStorage','Event','MouseEvent','CustomEvent','HTMLInputElement'])Object.defineProperty(globalThis,key,{configurable:true,value:(dom.window as any)[key]});
Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});
const {storage,setStoredData}=await import('../services/storage');
storage.getCurrentUser=()=>({id:'qa',role:'admin',status:'active',name:'اختبار'} as any); storage.getUiState=(_k:any,f:any)=>f; storage.saveUiState=()=>{};
const {CurriculumTreeView}=await import('../modules/curriculum/pages/CurriculumTreeView');
const {createRoot}=await import('react-dom/client');
const subjects:any[]=[{id:'s',name:'رياضيات',code:'MATH',description:'وصف المادة',icon:'Calculator'}];
const initialUnits:any[]=[{id:'u2',subjectId:'s',title:'الجبر',code:'U2',orderIndex:2},{id:'u1',subjectId:'s',title:'التفاضل',code:'U1',orderIndex:1}];
const lessons:any[]=[{id:'l1',subjectId:'s',unitId:'u1',title:'المشتقة'},{id:'l2',subjectId:'s',unitId:'u2',title:'المصفوفات'}];
const questions:any[]=[{id:'q',subjectId:'s',unitId:'u1',lessonId:'l1'},{id:'q',subjectId:'s',unitId:'u1'}];
let filterArgs:any, saved:any, deleted='', failSave=false, editorOpened=false;
function Harness(){const[units,setUnits]=useState(initialUnits);return <CurriculumTreeView subjects={subjects} units={units} lessons={lessons} questions={questions} onSaveSubject={()=>true} onDeleteSubject={()=>true} onSaveUnit={u=>{if(failSave)return false;saved=u;setUnits(p=>p.some(x=>x.id===u.id)?p.map(x=>x.id===u.id?u:x):[...p,u]);return true;}} onDeleteUnit={id=>{deleted=id;setUnits(p=>p.filter(x=>x.id!==id));return true;}} onSaveLesson={()=>{}} onDeleteLesson={()=>{}} onOpenLessonEditor={()=>{editorOpened=true;}} onOpenLessonQuestions={(...args)=>{filterArgs=args;}}/>}
const root=createRoot(document.getElementById('root')!); const settle=async(fn:()=>void)=>act(async()=>{fn();await new Promise(r=>setTimeout(r,15));});
const find=(text:string)=>Array.from(document.querySelectorAll<HTMLElement>('button,summary')).find(e=>e.textContent?.trim()===text||e.getAttribute('aria-label')===text);
const click=async(text:string)=>{const e=find(text);assert.ok(e,text);await settle(()=>e.click());};
const unitAction=async(label:string,action:string)=>{const summary=document.querySelector<HTMLElement>(`summary[aria-label="${label}"]`)!;assert.ok(summary);await settle(()=>summary.click());const button=Array.from(summary.closest('details')!.querySelectorAll<HTMLElement>('button')).find(e=>e.textContent?.trim()===action)!;assert.ok(button);await settle(()=>button.click());};
const input=async(el:HTMLInputElement,value:string)=>settle(()=>{Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype,'value')!.set!.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));});
await settle(()=>root.render(<Harness/>)); await click('عرض الوحدات');
assert.match(document.body.textContent!,/وصف المادة/); assert.match(document.body.textContent!,/2 وحدات/); assert.match(document.body.textContent!,/2 دروس/); assert.match(document.body.textContent!,/1 أسئلة مرتبطة/);
const titles=Array.from(document.querySelectorAll('.sd-unit-copy h3')).map(e=>e.textContent); assert.deepEqual(titles,['الجبر','التفاضل']);
await click('عرض أسئلة المادة'); assert.deepEqual(filterArgs,['s','','']);
const search=document.querySelector<HTMLInputElement>('[aria-label="بحث في وحدات المادة"]')!; await input(search,'U1'); assert.deepEqual(Array.from(document.querySelectorAll('.sd-unit-copy h3')).map(e=>e.textContent),['التفاضل']);
const scroll=document.querySelector('.overflow-y-auto') as HTMLElement; scroll.scrollTop=210; await click('عرض الدروس'); assert.match(document.body.textContent!,/المشتقة/); assert.equal(editorOpened,false);
await click('رياضيات'); assert.equal(document.querySelector<HTMLInputElement>('[aria-label="بحث في وحدات المادة"]')!.value,'U1'); assert.equal(scroll.scrollTop,210);
await input(document.querySelector<HTMLInputElement>('[aria-label="بحث في وحدات المادة"]')!,'لا يوجد'); assert.match(document.body.textContent!,/لا توجد وحدة مطابقة/); await click('مسح البحث');
await click('إضافة وحدة'); await click('إلغاء'); assert.equal(saved,undefined);
await click('إضافة وحدة'); const title=document.querySelector<HTMLInputElement>('input[placeholder^="مثال: الوحدة الأولى"]')!; await input(title,'وحدة جديدة'); failSave=true; await click('حفظ بيانات الوحدة'); assert.match(document.body.textContent!,/تعذر حفظ الوحدة/); assert.equal(saved,undefined); failSave=false; await click('حفظ بيانات الوحدة'); assert.equal(saved.title,'وحدة جديدة'); assert.ok(document.querySelector('.subject-detail'));
await unitAction('إجراءات وحدة التفاضل','تعديل الوحدة'); await input(document.querySelector<HTMLInputElement>('input[placeholder^="مثال: الوحدة الأولى"]')!,'تفاضل معدل'); await click('حفظ بيانات الوحدة'); assert.equal(saved.id,'u1'); assert.equal(saved.title,'تفاضل معدل');
await unitAction('إجراءات وحدة تفاضل معدل','حذف الوحدة'); assert.match(document.body.textContent!,/تبقى الأسئلة في البنك/); await click('إلغاء'); assert.equal(deleted,''); await unitAction('إجراءات وحدة تفاضل معدل','حذف الوحدة'); await click('نعم، تأكيد الحذف نهائياً'); assert.equal(deleted,'u1'); assert.ok(document.querySelector('.subject-detail'));
await settle(()=>root.unmount());
console.log('PASS subject details: counts/dedup, saved order, search, correct unit, return context, subject filter, add/edit/cancel/failure, safe delete');
for(const [k,v] of Object.entries({edutech_units_v1:initialUnits,edutech_lessons_v1:lessons,edutech_lesson_cards_v1:{l1:[{id:'c'}],l2:[{id:'c2'}]},edutech_questions_v1:questions.slice(0,1)}))setStoredData(k,v);
storage.deleteUnit('u1'); assert.deepEqual(storage.getUnits().map(u=>u.id),['u2']); assert.deepEqual(storage.getLessons().map(l=>l.id),['l2']); const q=storage.getQuestions()[0]; assert.equal(q.id,'q');assert.equal(q.unitId,'');assert.equal(q.lessonId,'');assert.ok(JSON.parse(localStorage.getItem('edutech_lesson_cards_v1')!).l2);
console.log('PASS unchanged unit deletion policy: child lessons/cards removed, bank questions retained/unlinked, unrelated unit intact');
