import assert from 'node:assert/strict';
import {registerHooks} from 'node:module';
import {JSDOM} from 'jsdom';
import React,{act,useState} from 'react';
import {defaultFallbackInView} from 'react-intersection-observer';
defaultFallbackInView(true);
registerHooks({load(url,ctx,next){if(url.endsWith('.css'))return{format:'module',source:'export default {}',shortCircuit:true};return next(url,ctx);}});
const dom=new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>',{url:'http://localhost',pretendToBeVisual:true});
for(const key of ['window','document','navigator','HTMLElement','Element','Node','MutationObserver','localStorage','sessionStorage','Event','MouseEvent','CustomEvent','HTMLInputElement'])Object.defineProperty(globalThis,key,{configurable:true,value:(dom.window as any)[key]});
Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true,requestAnimationFrame:(f:any)=>setTimeout(f,0),cancelAnimationFrame:clearTimeout});
const {storage,setStoredData}=await import('../services/storage');
let savedUi:any;
storage.getCurrentUser=()=>({id:'qa',role:'admin',status:'active',name:'اختبار'} as any); storage.getUiState=(_k:any,f:any)=>savedUi || f; storage.saveUiState=(_k:any,v:any)=>{savedUi=v;};
const {CurriculumTreeView}=await import('../modules/curriculum/pages/CurriculumTreeView');
const {LessonDetails,lessonHasPreviewContent,insertedQuestionIds}=await import('../modules/curriculum/components/LessonDetails');
const {createRoot}=await import('react-dom/client');
const subjects:any[]=[{id:'s',name:'مادة اختبار',code:'QA'}];
const units:any[]=[{id:'u',subjectId:'s',title:'وحدة اختبار'}];
const cards=Array.from({length:6},(_,i)=>({id:`c${i}`,title:`عنوان ${i}`,type:i===5?'questions':'text',body:i===5?JSON.stringify([{id:'q1',text:'سؤال مدرج'}]):'<p>محتوى</p>'}));
const initialLessons:any[]=[{id:'l1',subjectId:'s',unitId:'u',title:'درس أول',durationMinutes:90,status:'approved',contentParagraphs:cards,customField:'preserved'},{id:'l2',subjectId:'s',unitId:'u',title:'درس ثان',contentParagraphs:[]}];
const questions:any[]=[{id:'q1',subjectId:'s',lessonId:'l1',text:'احسب $x^2$',type:'essay',marks:2},{id:'q2',lessonIds:['l1'],text:'سؤال ثان',type:'true_false',marks:0},{id:'q3',lessonId:'l1',text:'سؤال ثالث',type:'essay'}];
questions.push(questions[0]);
let prepared='',previewed='',filter:any,saved:any,failSave=false,deleted='';
const nav={current:{}};
function Harness({loading=false,error=null}:{loading?:boolean;error?:string|null}={}){const[lessons,setLessons]=useState(initialLessons);return <CurriculumTreeView isLoading={loading} loadError={error} navigationState={nav} subjects={subjects} units={units} lessons={lessons} questions={questions} onSaveSubject={()=>true} onDeleteSubject={()=>true} onSaveUnit={()=>true} onDeleteUnit={()=>true} onSaveLesson={l=>{if(failSave)return false;saved=l;setLessons(p=>p.map(x=>x.id===l.id?l:x));return true;}} onDeleteLesson={id=>{deleted=id;setLessons(p=>p.filter(x=>x.id!==id));return true;}} onOpenLessonEditor={id=>{prepared=id;}} onOpenLessonPreview={id=>{previewed=id;}} onOpenLessonQuestions={(...args)=>{filter=args;}}/>}
const root=createRoot(document.getElementById('root')!); const settle=async(fn:()=>void)=>act(async()=>{fn();await new Promise(r=>setTimeout(r,25));});
const click=async(text:string,scope:ParentNode=document)=>{const e=Array.from(scope.querySelectorAll<HTMLElement>('button,summary')).find(e=>!e.closest('[hidden]')&&(e.textContent?.trim()===text||e.getAttribute('aria-label')===text));assert.ok(e,text);await settle(()=>e.click());};
const input=async(el:HTMLInputElement,value:string)=>settle(()=>{Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype,'value')!.set!.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));});
await settle(()=>root.render(<Harness/>)); await click('عرض الوحدات'); await click('عرض الدروس');
await click('إعداد الدرس');assert.equal(prepared,'l1');assert.equal(document.querySelector('.lesson-detail'),null);
const scroll=document.querySelector('.overflow-y-auto') as HTMLElement;scroll.scrollTop=145;
await click('درس أول');
assert.deepEqual(Array.from(document.querySelectorAll('.ld-cards li')).map(e=>e.textContent),['1عنوان 0','2عنوان 1','3عنوان 2','4عنوان 3']);
assert.match(document.querySelector('.ld-stats')!.textContent!,/90 دقيقة6 بطاقات3 أسئلة مرتبطةمعتمد/);
assert.doesNotMatch(document.querySelector('.ld-stats')!.textContent!,/منشور/);
assert.match(document.querySelector('.ld-remaining')!.textContent!,/2 بطاقات/);
assert.equal(document.querySelectorAll('.ld-question').length,2);
assert.match(document.querySelector('.ld-question')!.textContent!,/مدرج في محتوى الدرس/);
assert.match(document.querySelectorAll('.ld-question')[1].textContent!,/0 درجاتمرتبط بالدرس/);
await settle(()=>document.querySelector<HTMLElement>('.ld-question summary')!.click()); assert.ok(document.querySelector('.ld-question[open] .katex'),'expanded equation uses existing renderer');
await click('عرض جميع الأسئلة (3)');assert.equal(document.querySelectorAll('.ld-question').length,3);
await click('معاينة الدرس');assert.equal(previewed,'l1');
await click('إعداد الدرس');assert.equal(prepared,'l1');
await click('إدارة في بنك الأسئلة');assert.deepEqual(filter,['s','u','l1']);
await click('تعديل البيانات');await click('إلغاء');assert.equal(saved,undefined);
await click('تعديل البيانات');const title=document.querySelector<HTMLInputElement>('input[placeholder*="عنوان"]') || Array.from(document.querySelectorAll<HTMLInputElement>('input')).find(e=>e.value==='درس أول')!;await input(title,'درس معدل');failSave=true;
await click('حفظ بيانات الدرس');assert.match(document.body.textContent!,/تعذر حفظ الدرس/);assert.equal(title.value,'درس معدل');failSave=false;await click('حفظ بيانات الدرس');assert.equal(saved.id,'l1');assert.equal(saved.customField,'preserved');assert.deepEqual(saved.contentParagraphs,cards);
scroll.scrollTop=260;await settle(()=>root.render(<div/>));await settle(()=>root.render(<Harness/>));assert.equal((document.querySelector('.overflow-y-auto') as HTMLElement).scrollTop,260,'return restores lesson position after parent route remount');
await click('وحدة اختبار',document.querySelector('.ld-breadcrumb')!);assert.equal((document.querySelector('.overflow-y-auto') as HTMLElement).scrollTop,145);
await click('درس ثان');assert.match(document.querySelector('.ld-stats')!.textContent!,/0 بطاقات0 أسئلة/);assert.doesNotMatch(document.querySelector('.ld-stats')!.textContent!,/دقيقة/);assert.match(document.body.textContent!,/لا توجد بطاقات بعد/);assert.match(document.body.textContent!,/لا توجد أسئلة مرتبطة/);assert.equal((Array.from(document.querySelectorAll('button')).find(e=>e.textContent==='معاينة الدرس') as HTMLButtonElement).disabled,true);
await click('إعداد الدرس');assert.equal(prepared,'l2');await click('إجراءات الدرس');await click('حذف الدرس');await click('إلغاء');assert.equal(deleted,'');await click('حذف الدرس');await click('نعم، تأكيد الحذف نهائياً');assert.equal(deleted,'l2');assert.equal(document.querySelector('.lesson-detail'),null);
assert.equal(lessonHasPreviewContent({...initialLessons[0],contentParagraphs:[{body:'<p><br></p>'}]}),false);
assert.equal(lessonHasPreviewContent({...initialLessons[0],contentParagraphs:[{body:'<img src="x"/>'}]}),true);
assert.deepEqual([...insertedQuestionIds(initialLessons[0])],['q1']);
await click('درس أول');
await settle(()=>root.render(<Harness loading/>)); assert.match(document.querySelector('[role="status"]')!.textContent!,/جارٍ تحميل/); assert.equal(document.querySelector('.lesson-detail'),null);
await settle(()=>root.render(<Harness error="تعذر تحميل بيانات الدرس"/>)); assert.match(document.querySelector('[role="alert"]')!.textContent!,/تعذر تحميل/); assert.equal(document.querySelector('.lesson-detail'),null);
await settle(()=>root.unmount());
for(const [k,v] of Object.entries({edutech_lessons_v1:initialLessons,edutech_lesson_cards_v1:{l1:cards,l2:[]},edutech_questions_v1:questions.slice(0,3)}))setStoredData(k,v);
storage.deleteLesson('l1'); assert.equal(storage.getQuestions().length,3); assert.ok(storage.getQuestions().every(q=>q.lessonId!=='l1'&&!q.lessonIds?.includes('l1'))); assert.deepEqual(storage.getLessons().map(l=>l.id),['l2']);
console.log('PASS actual lesson deletion policy: bank questions retained and unlinked, unrelated lesson retained');
console.log('PASS lesson details: two lessons, cards order/counts, dedup, insertion vs linking, question expansion/math, exact route IDs, edit/cancel/failure, remount/scroll restoration, empty preview, delete/cancel');
