import {
  Subject,
  Unit,
  Lesson,
  Question,
  PrintTemplate,
  ExamTemplate,
  Exam,
  Cycle,
  User,
  AuditLog,
  SystemSettings,
} from "../types/index";

export const initialSubjects: Subject[] = [
  {
    id: "sub-1",
    code: "MATH101",
    name: "الرياضيات العامة",
    color: "#2563eb",
    icon: "Calculator",
    description: "منهاج التفاضل والتكامل والمصفوفات والتطبيقات الهندسيّة.",
    status: "active",
    totalMarks: 100,
    progressPercentage: 85,
  },
  {
    id: "sub-2",
    code: "PHYS201",
    name: "الفيزياء الحديثة",
    color: "#059669",
    icon: "Zap",
    description:
      "ميكانيكا الأجسام، الديناميكا الحرارية، والموجات الكهرومغناطيسية.",
    status: "active",
    totalMarks: 100,
    progressPercentage: 70,
  },
  {
    id: "sub-3",
    code: "CHEM101",
    name: "الكيمياء العامة والتحليلية",
    color: "#dc2626",
    icon: "FlaskConical",
    description: "موازنة المعادلات، الحموض والأسس، والحسابات الكيميائية.",
    status: "active",
    totalMarks: 100,
    progressPercentage: 75,
  },
  {
    id: "sub-4",
    code: "BIO101",
    name: "علم الأحياء واللغة العربية",
    color: "#16a34a",
    icon: "Dna",
    description: "قواعد اللغة والإعراب وتركيب الخلية ووظائفها.",
    status: "active",
    totalMarks: 100,
    progressPercentage: 60,
  },
  {
    id: "sub-5",
    code: "CS101",
    name: "مقدمة في البرمجة",
    color: "#7c3aed",
    icon: "Code",
    description: "أساسيات الخوارزميات والبرمجة بلغة بايثون.",
    status: "active",
    totalMarks: 100,
    progressPercentage: 90,
  },
  {
    id: "sub-6",
    code: "ENG101",
    name: "اللغة الإنجليزية (م1)",
    color: "#0284c7",
    icon: "Languages",
    description: "تطوير مهارات القراءة والكتابة والاستماع.",
    status: "active",
    totalMarks: 100,
    progressPercentage: 50,
  },
];

export const initialUnits: Unit[] = [
  // الرياضيات
  {
    id: "unit-101",
    subjectId: "sub-1",
    code: "U1",
    title: "الوحدة الأولى: التفاضل وتطبيقاته",
    description: "دراسة المشتقات العليا وتطبيقات القيمة القصوى وهندسية المماس.",
    orderIndex: 1,
    status: "active",
  },
  {
    id: "unit-102",
    subjectId: "sub-1",
    code: "U2",
    title: "الوحدة الثانية: التكامل المحدد وغير المحدد",
    description: "قوانين التكامل بالتعويض، بالأجزاء، وحساب المساحات والحجوم.",
    orderIndex: 2,
    status: "active",
  },
  {
    id: "unit-103",
    subjectId: "sub-1",
    code: "U3",
    title: "الوحدة الثالثة: المصفوفات والمحددات والأنظمة الخطية",
    description:
      "دراسة شاملة ورسمية للمصفوفات، المحددات، النظير الضربي، وحل أنظمة المعادلة الخطية بـ 3 مجاهيل والقيم الذاتية.",
    orderIndex: 3,
    status: "active",
  },
  // الفيزياء
  {
    id: "unit-201",
    subjectId: "sub-2",
    code: "U1",
    title: "الوحدة الأولى: الميكانيكا والديناميكا",
    description: "قوانين نيوتن في الحركة، الشغل والطاقة المحفوظة.",
    orderIndex: 1,
    status: "active",
  },
  {
    id: "unit-202",
    subjectId: "sub-2",
    code: "U2",
    title: "الوحدة الثانية: الكهرباء والمغناطيسية",
    description: "قانون أوم، الدوائر الكهربائية المركبة، والحث الكهرومغناطيسي.",
    orderIndex: 2,
    status: "active",
  },
  // الكيمياء
  {
    id: "unit-301",
    subjectId: "sub-3",
    code: "U1",
    title: "الوحدة الأولى: موازنة المعادلات والحسابات الكيميائية",
    description: "قوانين حفظ الكتلة وتفاعلات الاحتراق والمعاملات المتوازنة.",
    orderIndex: 1,
    status: "active",
  },
  {
    id: "unit-302",
    subjectId: "sub-3",
    code: "U2",
    title: "الوحدة الثانية: الحموض والأسس والمحاليل المائية",
    description: "نظريات الحموض والأسس، الرقم الهيدروجيني pH، والمحاليل المنظمة والمعايرة.",
    orderIndex: 2,
    status: "active",
  },
  // اللغة العربية والأحياء
  {
    id: "unit-401",
    subjectId: "sub-4",
    code: "U1",
    title: "الوحدة الأولى: قواعد النحو والإعراب",
    description:
      "المرفوعات والمنصوبات والمجرورات، وأحكام الجملة الاسمية والفعلية.",
    orderIndex: 1,
    status: "active",
  },
  // البرمجة
  {
    id: "unit-501",
    subjectId: "sub-5",
    code: "U1",
    title: "الوحدة الأولى: أساسيات الخوارزميات وبايثون",
    description: "المتغيرات، الجمل الشرطية، الحلقات التكرارية، والدوال.",
    orderIndex: 1,
    status: "active",
  },
  // الإنجليزية
  {
    id: "unit-601",
    subjectId: "sub-6",
    code: "U1",
    title: "Unit 1: Grammar & Reading Comprehension",
    description: "Tenses, vocabulary in context, and comprehension reading skills.",
    orderIndex: 1,
    status: "active",
  },
];

export const initialLessons: Lesson[] = [
  // دروس الرياضيات الوحدة 1
  {
    id: "les-101-1",
    unitId: "unit-101",
    subjectId: "sub-1",
    title: "مفهوم المشتقة الأولى وقواعد الاشتقاق الأساسية",
    orderIndex: 1,
    durationMinutes: 90,
    objectives: [
      "أن يستنتج الطالب التعريف العام للمشتقة الأولى باستخدام النهاية.",
      "أن يطبق قواعد اشتقاق دالة القوة ودالة حاصل الضرب والقسمة.",
      "أن يحل مسائل هندسية لحساب ميل المماس.",
    ],
    status: "approved",
    contentParagraphs: [
      {
        id: "p-title",
        title: "الدرس الأول: مفهوم المشتقة الأولى وقواعد الاشتقاق الأساسية",
        body: "<p><strong>المادة:</strong> الرياضيات التخصصية &nbsp;|&nbsp; <strong>الوحدة الأولى:</strong> التفاضل وتطبيقاته &nbsp;|&nbsp; <strong>المستوى:</strong> الصف الثاني عشر العلمي</p>",
        type: "title",
      },
      {
        id: "p-obj",
        title: "أهداف ومخرجات التعلم المقررة",
        body: "<ul><li>أن يستنتج الطالب التعريف الرياضي العام للمشتقة الأولى كقيمة نهاية معدل التغير.</li><li>أن يطبق القواعد الجبرية لاشتقاق دالة القوة، الثابت، المجموع، وحاصل الضرب والقسمة.</li><li>أن يستخدم جدول مشتقات الدوال المثلثية والأساسية في حل المسائل التطبيقية.</li><li>أن يميز حالات عدم قابلية الاشتقاق هندسياً وجبرياً.</li></ul>",
        type: "objectives",
      },
      {
        id: "p-def",
        title: "المفهوم الرياضي للمشتقة الأولى (First Derivative Definition)",
        body: "<p>تُعرّف المشتقة الأولى للدالة $f(x)$ عند النقطة $x$ بأنها نهاية معدل التغير عندما يقترب التغير في المتغير المستقل $h$ من الصفر، وتُعطى بالصيغة الرياضية التالية:</p><p align='center'>$$f'(x) = \\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h}$$</p><p>وتُمثّل هندسياً <strong>ميل المماس</strong> لمنحنى الدالة $y = f(x)$ عند النقطة $(x, f(x))$.</p>",
        type: "concepts",
      },
      {
        id: "p-rules",
        title: "قواعد الاشتقاق الجبرية الأساسية",
        body: "<p>لتسهيل حساب المشتقات دون اللجوء للتعريف العام بالنهايات في كل مرة، نعتمد على القواعد الجبرية المبرهنة التالية:</p><ol><li><strong>مشتقة الدالة الثابتة:</strong> إذا كانت $f(x) = c$ حيث $c \\in \\mathbb{R}$، فإن $f'(x) = 0$.</li><li><strong>مشتقة دالة القوة:</strong> إذا كانت $f(x) = x^n$ حيث $n \\in \\mathbb{Q}$، فإن $f'(x) = n x^{n-1}$.</li><li><strong>مشتقة ثابت مضروب في دالة:</strong> $[c \\cdot f(x)]' = c \\cdot f'(x)$.</li><li><strong>مشتقة مجموع وفرق دالتين:</strong> $[f(x) \\pm g(x)]' = f'(x) \\pm g'(x)$.</li><li><strong>مشتقة حاصل ضرب دالتين:</strong> $[u(x) \\cdot v(x)]' = u'(x)v(x) + u(x)v'(x)$.</li><li><strong>مشتقة حاصل قسمة دالتين:</strong> $\\left[\\frac{u(x)}{v(x)}\\right]' = \\frac{u'(x)v(x) - u(x)v'(x)}{[v(x)]^2} \\quad (v(x) \\neq 0)$.</li></ol>",
        type: "explanation",
      },
      {
        id: "p-table",
        title: "جدول مشتقات الدوال القياسية والمثلثية",
        body: "<table><thead><tr><th style='text-align:center;'>م</th><th style='text-align:center;'>الدالة الأصلية $f(x)$</th><th style='text-align:center;'>المشتقة الأولى $f'(x)$</th><th style='text-align:center;'>شروط ومجال الاشتقاق</th></tr></thead><tbody><tr><td style='text-align:center;'>1</td><td>$f(x) = \\sin(x)$</td><td>$f'(x) = \\cos(x)$</td><td>مستمرة وقابلة للاشتقاق على $\\mathbb{R}$</td></tr><tr><td style='text-align:center;'>2</td><td>$f(x) = \\cos(x)$</td><td>$f'(x) = -\\sin(x)$</td><td>مستمرة وقابلة للاشتقاق على $\\mathbb{R}$</td></tr><tr><td style='text-align:center;'>3</td><td>$f(x) = \\tan(x)$</td><td>$f'(x) = \\sec^2(x)$</td><td>$x \\neq \\frac{\\pi}{2} + k\\pi, \\; k \\in \\mathbb{Z}$</td></tr><tr><td style='text-align:center;'>4</td><td>$f(x) = \\sqrt{x}$</td><td>$f'(x) = \\frac{1}{2\\sqrt{x}}$</td><td>$x > 0$ (غير قابلة للاشتقاق عند $x=0$)</td></tr></tbody></table>",
        type: "tables",
      },
      {
        id: "p-example",
        title: "مثال تطبيقي محلول: إيجاد معادلة المماس",
        body: "<p><strong>نص المسألة:</strong> أوجد معادلة مماس منحنى الدالة $f(x) = 2x^3 - 3x^2 + 5$ عند النقطة التي إحداثيها السيني $x_0 = 2$.</p><hr/><p><strong>خطوات الحل النموذجي:</strong></p><ol><li><strong>إيجاد النقطة $(x_0, y_0)$:</strong><br/>$$y_0 = f(2) = 2(2)^3 - 3(2)^2 + 5 = 2(8) - 3(4) + 5 = 16 - 12 + 5 = 9$$<br/>إذن نقطة التماس هي $(2, 9)$.</li><li><strong>إيجاد ميل المماس $m = f'(2)$:</strong><br/>نشتق الدالة أولاً: $f'(x) = 6x^2 - 6x$<br/>نعوض $x = 2$: $m = f'(2) = 6(2)^2 - 6(2) = 24 - 12 = 12$.</li><li><strong>كتابة معادلة المماس:</strong><br/>الصيغة العامة: $y - y_0 = m(x - x_0)$<br/>التعويض: $y - 9 = 12(x - 2) \\implies y = 12x - 24 + 9 \\implies y = 12x - 15$.</li></ol>",
        type: "examples",
      },
      {
        id: "p-note",
        title: "إضاءة تعليمية وتنبيه هام: قابلية الاشتقاق والاتصال",
        body: "<p><strong>قاعدة ذهبية:</strong> كل دالة قابلة للاشتقاق عند نقطة تكون بالضرورة متصلة عندها، ولكن <em>العكس ليس صحيحاً دائماً</em>.<br/><strong>حالات عدم وجود المشتقة:</strong></p><ul><li>نقاط الرؤوس الحادة أو الانكسار (مثل دالة القيمة المطلقة عند الصفر).</li><li>نقاط المماس الرأسي (حيث يكون الميل غير معرّف).</li><li>نقاط عدم الاتصال والانفصال.</li></ul>",
        type: "notes",
      },
      {
        id: "p-act",
        title: "نشاط تدريبي للطالب (تمارين ذاتية)",
        body: "<p>احسب المشتقة الأولى للدوال التالية موضحاً خطوات الحل:</p><ol><li>$g(x) = (3x^2 - 1)(2x + 5)$</li><li>$h(x) = \\frac{x^2 + 1}{x - 3} \\quad (x \\neq 3)$</li><li>$k(x) = x^2 \\sin(x)$</li></ol>",
        type: "activities",
      },
    ],
  },
  {
    id: "les-101-2",
    unitId: "unit-101",
    subjectId: "sub-1",
    title: "تطبيقات القيم القصوى الرسمية والتقريبية",
    orderIndex: 2,
    durationMinutes: 120,
    objectives: [
      "تحديد النقاط الحرجة للدالة",
      "اختبار المشتقة الثانية لتحديد نوع القيمة القصوى",
    ],
    status: "approved",
  },
  // دروس الرياضيات الوحدة 2 (التكامل)
  {
    id: "les-102-1",
    unitId: "unit-102",
    subjectId: "sub-1",
    title: "مفهوم التكامل غير المحدد وقواعد التكامل والتعويض",
    orderIndex: 1,
    durationMinutes: 90,
    objectives: [
      "فهم مفهوم الدالة الأصلية والتكامل غير المحدد",
      "تطبيق قواعد تكامل القوى والدوال الأساسية والتكامل بالتعويض وبالأجزاء",
    ],
    status: "approved",
    contentParagraphs: [
      {
        id: "p102-1",
        title: "📘 مفهوم الدالة الأصلية والتكامل غير المحدد",
        type: "concept",
        body: "<p>التكامل غير المحدد هو العملية العكسية للاشتقاق $\\int f(x) dx = F(x) + C$.</p>",
      },
    ],
  },
  {
    id: "les-102-2",
    unitId: "unit-102",
    subjectId: "sub-1",
    title: "التكامل المحدد وحساب المساحات المستوية والتطبيقات الهندسية",
    orderIndex: 2,
    durationMinutes: 110,
    objectives: [
      "حساب قيمة التكامل المحدد $\\int_a^b f(x)dx$",
      "حساب المساحات المحصورة بين منحنى الدالة ومحور السينات",
    ],
    status: "approved",
    contentParagraphs: [
      {
        id: "p102-2",
        title: "📐 النظرية الأساسية في التفاضل والتكامل",
        type: "concept",
        body: "<p>تقضي النظرية الأساسية بأن $\\int_a^b f(x) dx = F(b) - F(a)$.</p>",
      },
    ],
  },
  // دروس الرياضيات الوحدة 3 (المحددات والأنظمة الخطية)
  {
    id: "les-math-determinants",
    unitId: "unit-103",
    subjectId: "sub-1",
    title: "المحددات وطريقة كرامر وحل الأنظمة الخطية",
    orderIndex: 2,
    durationMinutes: 90,
    objectives: [
      "حساب محددات المصفوفات 2x2 و 3x3 باستخدام طريقة النشر",
      "حل أنظمة المعادلات الخطية بطريقة كرامر",
    ],
    status: "approved",
    contentParagraphs: [
      {
        id: "p103-det1",
        title: "📐 حساب المحددات وقاعدة كرامر",
        type: "concept",
        body: "<p>يتم حساب قيمة المحدد $\\Delta$ لتحديد قابلية النظام للحل باستخدام $\\Delta_x, \\Delta_y, \\Delta_z$.</p>",
      },
    ],
  },
  // دروس الفيزياء الوحدة 1
  {
    id: "les-201-1",
    unitId: "unit-201",
    subjectId: "sub-2",
    title: "قانون نيوتن الثاني في الحركة وحفظ الزخم",
    orderIndex: 1,
    durationMinutes: 90,
    objectives: [
      "حساب تسارع جسم تحت تأثير عدة قوى",
      "تطبيق قانون حفظ الزخم الخطى في التصادمات",
    ],
    status: "approved",
  },
  // دروس الكيمياء
  {
    id: "les-301-1",
    unitId: "unit-301",
    subjectId: "sub-3",
    title: "موازنة المعادلة الكيميائية وقوانين حفظ الكتلة",
    orderIndex: 1,
    durationMinutes: 90,
    objectives: [
      "موازنة المعادلات الكيميائية المعقدة",
      "حساب المولات والكتلة المولية",
    ],
    status: "review",
  },
  // 8 دروس لوحدة الحموض والأسس - الثالث الثانوي المهني
  {
    id: "les-chem-1",
    unitId: "unit-302",
    subjectId: "sub-3",
    title: "الدرس 1: المفاهيم والنظريات الأساسية للحموض والأسس",
    orderIndex: 1,
    durationMinutes: 90,
    objectives: [
      "أن يقارن الطالب بين نظريات أرهينيوس وبرونستد-لوري ولويس لتفسير السلوك الحمضي والأساسي.",
      "أن يحدد الأزواج المترافقة (حمض/أساس) في تفاعلات انتقال البروتون H+.",
      "أن يكتب المعادلات الكيميائية لتأين الحموض والأسس القوية والضعيفة.",
    ],
    status: "approved",
    contentParagraphs: [
      {
        id: "chem-p1",
        title: "نظرية برونستد-لوري للأزواج المترافقة",
        body: "تنص النظرية على أن الحمض هو كل مادة جزيئية أو أيونية قادرة على منح بروتون $H^+$، والأساس هو كل مادة قادرة على استقبال بروتون $H^+$. ينشأ عن ذلك زواج مترافق $\\text{حمض / أساس}$.",
        type: "concept",
      },
      {
        id: "chem-p2",
        title: "معادلة انتقال البروتون",
        body: "عند ذوبان غاز النشادر في الماء: $NH_3 + H_2O \\rightleftharpoons NH_4^+ + OH^-$، يلعب $NH_3$ دور الأساس ويتحول إلى حامض مرافق $NH_4^+$, بينما يلعب الماء دور الحمض المانح للبروتون.",
        type: "concept",
      },
    ],
  },
  {
    id: "les-chem-2",
    unitId: "unit-302",
    subjectId: "sub-3",
    title: "الدرس 2: قوة الحموض والأسس وثوابت التأين (Ka و Kb)",
    orderIndex: 2,
    durationMinutes: 90,
    objectives: [
      "أن يُميز بين الحموض والأسس القوية (التأين التام) والضعيفة (التأين الجزئي المتوازن).",
      "أن يكتب صياغة ثابت التأين Ka للحمض الضعيف وثابت التأين Kb للأساس الضعيف.",
      "أن يحسب درجة التأين α والنسبة المئوية للتأين في المحاليل المائية.",
    ],
    status: "approved",
    contentParagraphs: [
      {
        id: "chem-p3",
        title: "التأين التام والمحدود",
        body: "تتأين الحموض القوية كلياً مثل حمض الهيدروكلوريك $HCl + H_2O \\longrightarrow H_3O^+ + Cl^-$ بتركيز متساوٍ، بينما تتأين الحموض الضعيفة جزئياً مثل حمض الخل $CH_3COOH + H_2O \\rightleftharpoons H_3O^+ + CH_3COO^-$.",
        type: "concept",
      },
      {
        id: "chem-p4",
        title: "عبارة ثابت التأين Ka",
        body: "ثابت التأين للحمض الضعيف يُكتب بالشكل: $K_a = \\frac{[H_3O^+][CH_3COO^-]}{[CH_3COOH]}$ وهو مقياس مباشر لقوة الحمض الضعيف.",
        type: "summary",
      },
    ],
  },
  {
    id: "les-chem-3",
    unitId: "unit-302",
    subjectId: "sub-3",
    title: "الدرس 3: التأين الذاتي للماء والجداء الأيوني (Kw)",
    orderIndex: 3,
    durationMinutes: 90,
    objectives: [
      "أن يستنتج معادلة التأين الذاتي للماء النقي عند درجة حرارة 25°C.",
      "أن يطبق قانون الجداء الأيوني للماء Kw = [H3O+][OH-] = 10^-14.",
      "أن يحسب تركيز أيونات H3O+ و OH- لتحديد طبيعة المحلول المائي.",
    ],
    status: "approved",
    contentParagraphs: [
      {
        id: "chem-p5",
        title: "ظاهرة التفكك الذاتي للماء",
        body: "يسلك الماء سلوكاً أمفوتيرياً (متردداً) حيث تتفاعل جزيئتان لتكوين الهيدرونيوم والهيدروكسيد: $2H_2O \\rightleftharpoons H_3O^+ + OH^-$.",
        type: "concept",
      },
      {
        id: "chem-p6",
        title: "قانون Kw والطبيعة الحمضية والأساسية",
        body: "عند 25°C تكون قيمة $K_w = [H_3O^+][OH^-] = 10^{-14}$. يكون المحلول متعادلاً إذا كان $[H_3O^+] = [OH^-] = 10^{-7} \\text{ mol/L}$.",
        type: "summary",
      },
    ],
  },
  {
    id: "les-chem-4",
    unitId: "unit-302",
    subjectId: "sub-3",
    title: "الدرس 4: حسابات الرقم الهيدروجيني (pH) والرقم الهيدروكسيدي (pOH)",
    orderIndex: 4,
    durationMinutes: 120,
    objectives: [
      "أن يعرّف الرقم الهيدروجيني pH = -log[H3O+] والرقم الهيدروكسيدي pOH = -log[OH-].",
      "أن يبرهن وينفّذ العلاقة الأساسية pH + pOH = 14.",
      "أن يحل مسائل حسابية متنوعة لإيجاد pH للحموض والأسس القوية والضعيفة.",
    ],
    status: "approved",
    contentParagraphs: [
      {
        id: "chem-p7",
        title: "مقياس الأس الهيدروجيني pH",
        body: "يُعرّف الرقم الهيدروجيني باللوغاريتم السالب لتركيز أيون الهيدرونيوم: $pH = -\\log[H_3O^+]$، وبالتالي فإن $[H_3O^+] = 10^{-pH}$.",
        type: "concept",
      },
      {
        id: "chem-p8",
        title: "مسألة محلولة لحساب pH",
        body: "حساب $pH$ لمحلول هيدروكسيد الصوديوم $NaOH$ بتركيز $10^{-3} \\text{ M}$: تركيز $[OH^-] = 10^{-3} \\text{ M} \\Rightarrow pOH = 3 \\Rightarrow pH = 14 - 3 = 11$ (محلول أساسي قاسي).",
        type: "exercise",
      },
    ],
  },
  {
    id: "les-chem-5",
    unitId: "unit-302",
    subjectId: "sub-3",
    title:
      "الدرس 5: إماهة وتفاعل الأملاح في الماء (الأملاح المتعادلة والحمضية والأساسية)",
    orderIndex: 5,
    durationMinutes: 90,
    objectives: [
      "أن يحدد طبيعة المحلول المائي للأملاح (حمضي، أساسي، متعادل) بناءً على أصل الملح.",
      "أن يكتب معادلات إماهة وتحلل الأيونات المشتقة من حموض أو أسس ضعيفة مع الماء.",
      "أن يحسب قيمة pH لمحاليل الأملاح الحامضية والأساسية.",
    ],
    status: "approved",
    contentParagraphs: [
      {
        id: "chem-p9",
        title: "تحلل الأيونات مائياً (Hydrolysis)",
        body: "الأملاح الناتجة عن حمض ضعيف وأساس قوي (مثل خلات الصوديوم $CH_3COONa$) تتأين أولاً: $CH_3COONa \\longrightarrow CH_3COO^- + Na^+$، ثم تتفاعل أيونات الخلات الضعيفة مع الماء: $CH_3COO^- + H_2O \\rightleftharpoons CH_3COOH + OH^-$ مما يرفع الـ $pH$ عن 7.",
        type: "concept",
      },
    ],
  },
  {
    id: "les-chem-6",
    unitId: "unit-302",
    subjectId: "sub-3",
    title: "الدرس 6: المحاليل المنظمة (المحاليل المصدة / Buffer Solutions)",
    orderIndex: 6,
    durationMinutes: 90,
    objectives: [
      "أن يوضح تركيب المحلول المنظم (حمض ضعيف + ملحه، أو أساس ضعيف + ملحه).",
      "أن يشرح آلية عمل المحلول المنظم في مقاومة التغير المفاجئ في قيمة pH.",
      "أن يطبق معادلة هندرسون-هاسلبالخ لحساب pH للمزيج المنظم.",
    ],
    status: "approved",
    contentParagraphs: [
      {
        id: "chem-p10",
        title: "مفهوم المحلول المنظم ومعادلة هندرسون-هاسلبالخ",
        body: "هو محلول يقاوم التغيرات الشديدة في $pH$ عند إضافة كميات قليلة من حمض أو أساس، وتُحسب قيمته بالقانون: $pH = pK_a + \\log \\frac{[\\text{الملح}]}{[\\text{الحمض}]}$.",
        type: "concept",
      },
    ],
  },
  {
    id: "les-chem-7",
    unitId: "unit-302",
    subjectId: "sub-3",
    title: "الدرس 7: المعايرة الحجمية حمض-أساس ونقطة التكافؤ",
    orderIndex: 7,
    durationMinutes: 120,
    objectives: [
      "أن يشرح خطوات عملية المعايرة الحجمية وتحديد نقطة التكافؤ باستعمال المشعرات الكيميائية.",
      "أن يختار المشعر المناسب (مثل الفينول فثالين أو أورانج الميثيل) حسب مدى pH المعايرة.",
      "أن يحل المسائل الرقمية الخاصة بالمعايرة باستخدام قانون التكافؤ N1 V1 = N2 V2.",
    ],
    status: "approved",
    contentParagraphs: [
      {
        id: "chem-p11",
        title: "مبدأ المعايرة وقانون التكافؤ",
        body: "تفاعل التعادل الكيميائي: $HCl + NaOH \\longrightarrow NaCl + H_2O$. عند نقطة التكافؤ ينتهي التفاعل كلياً وتتحقق العلاقة: $C_A \\cdot V_A = C_B \\cdot V_B$.",
        type: "concept",
      },
    ],
  },
  {
    id: "les-chem-8",
    unitId: "unit-302",
    subjectId: "sub-3",
    title: "الدرس 8: المسائل العامة والتطبيقات المهنية والصناعية للحموض والأسس",
    orderIndex: 8,
    durationMinutes: 120,
    objectives: [
      "أن يحل مسائل امتحانية شاملة للبكالوريا المهنية تربط التأين بالـ pH والمعايرة.",
      "أن يربط مفاهيم الحموض والأسس بالتطبيقات الصناعية المهنية (المنظفات، البطاريات، التسميد الكيميائي).",
      "أن يلتزم بإجراءات الوقاية والسلامة عند handling الحموض والأسس المركزة.",
    ],
    status: "approved",
    contentParagraphs: [
      {
        id: "chem-p12",
        title: "التطبيقات الصناعية والمهنية للحموض والأسس",
        body: "تُستخدم الحموض والأسس في بطاريات السيارات (حمض الكبريتيك $H_2SO_4$)، وصناعة الصابون والمنظفات الكيماوية (هيدروكسيد الصوديوم $NaOH$)، مع مراعاة قواعد الأمان والسلامة المهنية والمخبرية.",
        type: "summary",
      },
    ],
  },
  // دروس الحاسوب والبرمجة
  {
    id: "les-501-1",
    unitId: "unit-501",
    subjectId: "sub-5",
    title: "مقدمة إلى لغة بايثون وهياكل البيانات الأساسية",
    orderIndex: 1,
    durationMinutes: 90,
    objectives: [
      "التعرف على بيئة عمل بايثون والمتغيرات وأنواع البيانات.",
      "استخدام القوائم والمجموعات والقواميس (Lists & Dictionaries).",
    ],
    status: "approved",
  },
  // دروس اللغة الإنجليزية
  {
    id: "les-601-1",
    unitId: "unit-601",
    subjectId: "sub-6",
    title: "English Tenses: Present Perfect and Past Simple",
    orderIndex: 1,
    durationMinutes: 60,
    objectives: [
      "Distinguish between Present Perfect and Past Simple in context.",
      "Use time markers accurately in academic writing.",
    ],
    status: "approved",
  },
  // دروس العربية
  {
    id: "les-401-1",
    unitId: "unit-401",
    subjectId: "sub-4",
    title: "إعراب الفاعل والمفعول به والأفعال الخمسة",
    orderIndex: 1,
    durationMinutes: 60,
    objectives: [
      "تمييز الفاعل والمفعول به في الجمل المعقدة",
      "إعراب الأفعال الخمسة بثبوت النون وحذفها",
    ],
    status: "approved",
  },
  // درس رياضيات تجريبي: المصفوفات والمحددات
  {
    id: "les-math-matrices",
    unitId: "unit-103",
    subjectId: "sub-1",
    title: "المصفوفات",
    orderIndex: 1,
    durationMinutes: 120,
    objectives: [
      "فهم مفهوم المصفوفة وأنواعها الرتبية (مربعة، صفية، عمودية، قطرية، صفرية، ومصفوفة الوحدة I).",
      "إتقان عمليات جمع وطرح وضرب المصفوفات وإيجاد مدورة المصفوفة A^T والمصفوفات المتناظرة.",
      "حساب محددات المصفوفات 2x2 و 3x3 وإيجاد النظير الضربي A^-1 والقيم الذاتية بالمعادلة المميزة.",
      "حل أنظمة المعادلات الخطية بـ 3 مجاهيل باستخدام طريقة كرامر وقاعدة المصفوفات."
    ],
    status: "approved",
    contentParagraphs: [
      {
        id: "mat-p1",
        title: "📘 1. مفهوم المصفوفة وتصنيف الأنواع الخاصة (Matrix Definition & Special Types)",
        type: "title",
        body: `<p>تُعرف <strong>المصفوفة</strong> $A_{m \\times n}$ بأنها تنظيم مستطيل من الأعداد مرتبة في $m$ صفاً و $n$ عموداً.</p>

<h3>أبرز الأنواع الخاصة للمصفوفات:</h3>
<ul>
  <li><strong>المصفوفة الصفية (Row Vector):</strong> $R = \\begin{bmatrix} 1 & -5 & 3 \\end{bmatrix}$ (رتبة $1 \\times 3$)</li>
  <li><strong>المصفوفة العمودية (Column Vector):</strong> $C = \\begin{bmatrix} x_1 \\\\ x_2 \\\\ x_3 \\end{bmatrix}$ (رتبة $3 \\times 1$)</li>
  <li><strong>المصفوفة المربعة 2×2:</strong> $A = \\begin{pmatrix} a_{11} & a_{12} \\\\ a_{21} & a_{22} \\end{pmatrix} = \\begin{pmatrix} 3 & -2 \\\\ 4 & 7 \\end{pmatrix}$</li>
  <li><strong>المصفوفة المربعة 3×3:</strong> $B = \\begin{bmatrix} 1 & 0 & 5 \\\\ -2 & 4 & 2 \\\\ 3 & -1 & 6 \\end{bmatrix}$</li>
  <li><strong>مصفوفة الوحدة $\\mathbf{I}_3$ والمصفوفة الصفرية $\\mathbf{O}$:</strong>
    $$\\mathbf{I}_3 = \\begin{bmatrix} 1 & 0 & 0 \\\\ 0 & 1 & 0 \\\\ 0 & 0 & 1 \\end{bmatrix}, \\quad \\mathbf{O}_{2 \\times 3} = \\begin{bmatrix} 0 & 0 & 0 \\\\ 0 & 0 & 0 \\end{bmatrix}$$
  </li>
</ul>`
      },
      {
        id: "mat-p2",
        title: "💡 2. المفاهيم الأساسية: المدورة وضرب المصفوفات (Transpose & Matrix Product)",
        type: "concepts",
        body: `<p>نستعرض هنا خواص مدورة المصفوفة $A^T$ والشرط اللازم لإمكانية الضرب:</p>

<h3>1. مدورة المصفوفة $A^T$ (Matrix Transpose):</h3>
<p>يتم تحويل الصفوف إلى أعمدة. إذا كانت $A = \\begin{bmatrix} 2 & 5 & 1 \\\\ -3 & 0 & 4 \\end{bmatrix}$ فإن مدورتها:</p>
$$A^T = \\begin{bmatrix} 2 & -3 \\\\ 5 & 0 \\\\ 1 & 4 \\end{bmatrix}$$
<p><strong>المصفوفة المتناظرة (Symmetric Matrix):</strong> تكون $A$ متناظرة إذا وفقط إذا كان $A = A^T \\iff a_{ij} = a_{ji}$.</p>

<h3>2. عملية ضرب مصفوفتين (Matrix Multiplication):</h3>
<p>يشترط لضرب $A_{m \\times k} \\cdot B_{k \\times n}$ أن يتساوى عدد أعمدة $A$ مع عدد صفوف $B$:</p>
$$\\begin{bmatrix} 1 & 2 \\\\ 3 & 4 \\end{bmatrix} \\begin{bmatrix} 5 & 6 \\\\ 7 & 8 \\end{bmatrix} = \\begin{bmatrix} 1 \\cdot 5 + 2 \\cdot 7 & 1 \\cdot 6 + 2 \\cdot 8 \\\\ 3 \\cdot 5 + 4 \\cdot 7 & 3 \\cdot 6 + 4 \\cdot 8 \\end{bmatrix} = \\begin{bmatrix} 19 & 22 \\\\ 43 & 50 \\end{bmatrix}$$`
      },
      {
        id: "mat-p3",
        title: "🧪 3. قواعد المحددات والكسور والنظير الضربي (Determinants & Inverse Matrix)",
        type: "math",
        body: `<p>تطبيق قوانين المحددات $\\det(A)$ وحساب النظير الضربي $A^{-1}$ بالكسور:</p>

<h3>1. محدد مصفوفة 2×2 و 3×3:</h3>
<ul>
  <li><strong>محدد 2×2:</strong> $\\det(A) = \\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix} = ad - bc$</li>
  <li><strong>محدد 3×3 بالنشر بحسب الصف الأول:</strong>
    $$|B| = \\begin{vmatrix} 3 & 1 & -2 \\\\ 2 & 0 & 4 \\\\ -1 & 5 & 2 \\end{vmatrix} = 3 \\begin{vmatrix} 0 & 4 \\\\ 5 & 2 \\end{vmatrix} - 1 \\begin{vmatrix} 2 & 4 \\\\ -1 & 2 \\end{vmatrix} + (-2) \\begin{vmatrix} 2 & 0 \\\\ -1 & 5 \\end{vmatrix}$$
    $$|B| = 3(0 - 20) - 1(4 - (-4)) - 2(10 - 0) = -60 - 8 - 20 = -88$$
  </li>
</ul>

<h3>2. قانون النظير الضربي $A^{-1}$ للمصفوفة القابلة للانعكاس:</h3>
<p>تكون المصفوفة غير شاذة (قابلة للانعكاس) إذا وفقط إذا كان $\\det(A) \\neq 0$:</p>
$$A^{-1} = \\frac{1}{\\det(A)} \\text{adj}(A) = \\begin{bmatrix} \\frac{d}{ad-bc} & \\frac{-b}{ad-bc} \\\\ \\frac{-c}{ad-bc} & \\frac{a}{ad-bc} \\end{bmatrix}$$`
      },
      {
        id: "mat-p4",
        title: "✅ 4. مثال تطبيقي: حل نظام معادلات خطية بـ 3 مجاهيل (System of Equations & Cramer)",
        type: "examples",
        body: `<p><strong>المسألة:</strong> أوجد مجموعة حل نظام المعادلات الخطية التالي باستخدام طريقة كرامر وقواعد المصفوفات:</p>

$$\\begin{cases} 2x + y - z = 8 \\\\ -x + 3y + 2z = 1 \\\\ 3x - y + 4z = 9 \\end{cases}$$

<h3>تمثيل الجملة بالصيغة المصفوفية $\\mathbf{A \\cdot X = B}$:</h3>
$$\\begin{bmatrix} 2 & 1 & -1 \\\\ -1 & 3 & 2 \\\\ 3 & -1 & 4 \\end{bmatrix} \\begin{bmatrix} x \\\\ y \\\\ z \\end{bmatrix} = \\begin{bmatrix} 8 \\\\ 1 \\\\ 9 \\end{bmatrix}$$

<h3>خطوات الحل التفصيلية:</h3>
<ol>
  <li><strong>حساب محدد المعاملات $\\Delta$:</strong>
    $$\\Delta = \\begin{vmatrix} 2 & 1 & -1 \\\\ -1 & 3 & 2 \\\\ 3 & -1 & 4 \\end{vmatrix} = 2(12 - (-2)) - 1(-4 - 6) - 1(1 - 9) = 28 + 10 + 8 = 46$$
  </li>
  <li><strong>حساب المحددات الفرعية وركام المجاهيل:</strong>
    <ul>
      <li>$\\Delta_x = \\begin{vmatrix} 8 & 1 & -1 \\\\ 1 & 3 & 2 \\\\ 9 & -1 & 4 \\end{vmatrix} = 138 \\implies x = \\frac{\\Delta_x}{\\Delta} = \\frac{138}{46} = 3$</li>
      <li>$\\Delta_y = \\begin{vmatrix} 2 & 8 & -1 \\\\ -1 & 1 & 2 \\\\ 3 & 9 & 4 \\end{vmatrix} = 46 \\implies y = \\frac{\\Delta_y}{\\Delta} = \\frac{46}{46} = 1$</li>
      <li>$\\Delta_z = \\begin{vmatrix} 2 & 1 & 8 \\\\ -1 & 3 & 1 \\\\ 3 & -1 & 9 \\end{vmatrix} = -46 \\implies z = \\frac{\\Delta_z}{\\Delta} = \\frac{-46}{46} = -1$</li>
    </ul>
  </li>
</ol>
<p><strong>الثنائية الثلاثية للحل:</strong> $\\mathbf{(x, y, z) = (3, 1, -1)}$</p>`
      },
      {
        id: "mat-p5",
        title: "📝 5. ملاحظات وحالات خاصة: المعادلة المميزة والقيم الذاتية (Eigenvalues & Trace)",
        type: "notes",
        body: `<p>تنبيه هام للطلاب حول حساب القيم الذاتية والأثر $\\text{tr}(A)$:</p>

<h3>1. المعادلة المميزة (Characteristic Equation):</h3>
<p>تُحسب القيم الذاتية $\\lambda$ للمصفوفة $A = \\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix}$ من حل المعادلة التربيعية:</p>
$$\\begin{vmatrix} a - \\lambda & b \\\\ c & d - \\lambda \\end{vmatrix} = \\lambda^2 - \\text{tr}(A)\\lambda + \\det(A) = 0$$

<p>حيث أثر المصفوفة هو مجموع عناصر القطر الرئيسي $\\text{tr}(A) = a + d$.</p>

<h3>2. صيغة الجذر التربيعي للقيمة الذاتية:</h3>
$$\\lambda_{1,2} = \\frac{\\text{tr}(A) \\pm \\sqrt{[\\text{tr}(A)]^2 - 4\\det(A)}}{2}$$`
      },
      {
        id: "mat-p6",
        title: "⚡ 6. تطبيق حوسبة وتكوين مصفوفات بلغة بايثون (NumPy Operations)",
        type: "activities",
        body: `<p>تطبيق عملي برمجياً للتحقق من نتائج العمليات على المصفوفات والمحددات والنظير الضربي:</p>

<pre><code class="language-python">import numpy as np

# 1. تعريف المصفوفات A و B
A = np.array([[2, 1, -1],
              [-1, 3, 2],
              [3, -1, 4]])
B = np.array([8, 1, 9])

# 2. حساب المحدد والنظير الضربي ومتجه الحل
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
X = np.linalg.solve(A, B)

print("محدد المصفوفة:", round(det_A))
print("متجه الحلول (x, y, z):", np.round(X))
</code></pre>`
      },
      {
        id: "mat-p7",
        title: "7. أسئلة وتقويم شامل لدرس المصفوفات (Evaluation Questions)",
        type: "questions",
        body: JSON.stringify([
          {
            id: "q-mat-1",
            type: "mcq",
            text: "إذا كانت المصفوفة $A = \\begin{bmatrix} 4 & 2 \\\\ 1 & 3 \\end{bmatrix}$، فإن محدد المصفوفة $\\det(A)$ يساوي:",
            answer: "10",
            distractors: ["10", "14", "12", "8"],
            difficulty: "easy",
            score: 1,
            author: "المعلم"
          },
          {
            id: "q-mat-2",
            type: "mcq",
            text: "النظير الضربي $A^{-1}$ للمصفوفة $A = \\begin{bmatrix} 2 & 0 \\\\ 0 & 5 \\end{bmatrix}$ هو:",
            answer: "$\\begin{bmatrix} \\frac{1}{2} & 0 \\\\ 0 & \\frac{1}{5} \\end{bmatrix}$",
            distractors: [
              "$\\begin{bmatrix} \\frac{1}{2} & 0 \\\\ 0 & \\frac{1}{5} \\end{bmatrix}$",
              "$\\begin{bmatrix} 5 & 0 \\\\ 0 & 2 \\end{bmatrix}$",
              "$\\begin{bmatrix} -2 & 0 \\\\ 0 & -5 \\end{bmatrix}$",
              "$\\begin{bmatrix} 1 & 0 \\\\ 0 & 1 \\end{bmatrix}$"
            ],
            difficulty: "medium",
            score: 2,
            author: "المعلم"
          },
          {
            id: "q-mat-3",
            type: "essay",
            text: "أوجد حل نظام المعادلتين الخطيتين التالي باستخدام النظير الضربي للمصفوفات:\n$$\\begin{cases} x + 2y = 5 \\\\ 3x - y = 1 \\end{cases}$$",
            answer: "صيغة المصفوفة: $\\begin{bmatrix} 1 & 2 \\\\ 3 & -1 \\end{bmatrix} \\begin{bmatrix} x \\\\ y \\end{bmatrix} = \\begin{bmatrix} 5 \\\\ 1 \\end{bmatrix}$\nالمحدد: $\\det = -1 - 6 = -7$\nالنظير الضربي: $A^{-1} = -\\frac{1}{7} \\begin{bmatrix} -1 & -2 \\\\ -3 & 1 \\end{bmatrix} = \\begin{bmatrix} \\frac{1}{7} & \\frac{2}{7} \\\\ \\frac{3}{7} & -\\frac{1}{7} \\end{bmatrix}$\nالحل: $x = 1, y = 2$.",
            difficulty: "hard",
            score: 3,
            author: "المعلم"
          }
        ])
      }
    ]
  },
];

export const initialQuestions: Question[] = [
  // أسئلة درس المصفوفات
  {
    id: "q-mat-1",
    subjectId: "sub-1",
    unitId: "unit-103",
    lessonId: "les-math-matrices",
    type: "mcq",
    text: "إذا كانت المصفوفة $A = \\begin{bmatrix} 4 & 2 \\\\ 1 & 3 \\end{bmatrix}$، فإن محدد المصفوفة $\\det(A)$ يساوي:",
    answer: "10",
    difficulty: "easy",
    importance: 5,
    tags: ["مصفوفات", "محددات", "رياضيات"],
    isPastCycle: true,
    pastCyclesInfo: "دورة 2024 - أصلية",
    occurrencesCount: 2,
    futureProbability: 95,
    lastUsedDate: "2025-06-20",
    finalWeightScore: 4.9,
    createdAt: "2025-06-01T10:00:00Z",
    distractors: [
      { id: "d1", text: "10", isCorrect: true, rationale: "4*3 - 2*1 = 12 - 2 = 10" },
      { id: "d2", text: "14", isCorrect: false, rationale: "جمع القطرين بدلاً من الطرح" },
      { id: "d3", text: "12", isCorrect: false, rationale: "ضرب القطر الرئيسي فقط" },
      { id: "d4", text: "8", isCorrect: false, rationale: "خطأ في عملية الطرح" }
    ]
  },
  {
    id: "q-mat-2",
    subjectId: "sub-1",
    unitId: "unit-103",
    lessonId: "les-math-matrices",
    type: "mcq",
    text: "النظير الضربي $A^{-1}$ للمصفوفة $A = \\begin{bmatrix} 2 & 0 \\\\ 0 & 5 \\end{bmatrix}$ هو:",
    answer: "$\\begin{bmatrix} \\frac{1}{2} & 0 \\\\ 0 & \\frac{1}{5} \\end{bmatrix}$",
    difficulty: "medium",
    importance: 5,
    tags: ["مصفوفات", "نظير ضربي", "رياضيات"],
    isPastCycle: false,
    occurrencesCount: 1,
    futureProbability: 88,
    lastUsedDate: "2025-05-10",
    finalWeightScore: 4.2,
    createdAt: "2025-06-01T10:00:00Z",
    distractors: [
      { id: "d1", text: "$\\begin{bmatrix} \\frac{1}{2} & 0 \\\\ 0 & \\frac{1}{5} \\end{bmatrix}$", isCorrect: true, rationale: "نظير مصفوفة قطرية هو مقلوب عناصر القطر" },
      { id: "d2", text: "$\\begin{bmatrix} 5 & 0 \\\\ 0 & 2 \\end{bmatrix}$", isCorrect: false, rationale: "تبديل العناصر فقط" },
      { id: "d3", text: "$\\begin{bmatrix} -2 & 0 \\\\ 0 & -5 \\end{bmatrix}$", isCorrect: false, rationale: "تغيير الإشارة بدلاً من المقلوب" },
      { id: "d4", text: "$\\begin{bmatrix} 1 & 0 \\\\ 0 & 1 \\end{bmatrix}$", isCorrect: false, rationale: "مصفوفة الوحدة" }
    ]
  },
  {
    id: "q-mat-3",
    subjectId: "sub-1",
    unitId: "unit-103",
    lessonId: "les-math-matrices",
    type: "essay",
    text: "أوجد حل نظام المعادلتين الخطيتين التالي باستخدام النظير الضربي للمصفوفات:\n$$\\begin{cases} x + 2y = 5 \\\\ 3x - y = 1 \\end{cases}$$",
    answer: "صيغة المصفوفة: $\\begin{bmatrix} 1 & 2 \\\\ 3 & -1 \\end{bmatrix} \\begin{bmatrix} x \\\\ y \\end{bmatrix} = \\begin{bmatrix} 5 \\\\ 1 \\end{bmatrix}$\nالمحدد: $\\det = -1 - 6 = -7$\nالنظير الضربي: $A^{-1} = -\\frac{1}{7} \\begin{bmatrix} -1 & -2 \\\\ -3 & 1 \\end{bmatrix} = \\begin{bmatrix} \\frac{1}{7} & \\frac{2}{7} \\\\ \\frac{3}{7} & -\\frac{1}{7} \\end{bmatrix}$\nالحل: $x = 1, y = 2$.",
    difficulty: "hard",
    importance: 5,
    tags: ["مصفوفات", "أنظمة خطية", "مسألة محلولة"],
    isPastCycle: true,
    pastCyclesInfo: "دورة 2023 - ثانية",
    occurrencesCount: 4,
    futureProbability: 96,
    lastUsedDate: "2025-06-01",
    finalWeightScore: 5.0,
    createdAt: "2025-06-01T10:00:00Z"
  },
  // 1. MCQ
  {
    id: "q-1",
    subjectId: "sub-1",
    unitId: "unit-101",
    lessonId: "les-101-1",
    type: "mcq",
    text: "إذا كانت الدالة $f(x) = 3x^2 + 5x - 7$، فإن المشتقة الأولى $f'(x)$ عند $x = 2$ تساوي:",
    answer: "$17$",
    difficulty: "medium",
    importance: 5,
    tags: ["مشتقات", "تفاضل", "تطبيق مباشر"],
    isPastCycle: true,
    pastCyclesInfo: "دورة 2024 - الفصل الأول",
    occurrencesCount: 3,
    futureProbability: 92,
    lastUsedDate: "2025-06-15",
    finalWeightScore: 4.8,
    distractors: [
      {
        id: "d1",
        text: "$12$",
        isCorrect: false,
        rationale: "خطأ في نسيان مشتقة الحد الثاني 5x",
      },
      {
        id: "d2",
        text: "$17$",
        isCorrect: true,
        rationale: "f'(x) = 6x + 5 -> 6(2)+5 = 17",
      },
      {
        id: "d3",
        text: "$11$",
        isCorrect: false,
        rationale: "خطأ في ضرب 3*2 بدلاً من 6*2",
      },
      {
        id: "d4",
        text: "$22$",
        isCorrect: false,
        rationale: "خطأ في تعويض x في الدالة الأصلية بدلاً من المشتقة",
      },
    ],
    createdAt: "2025-01-10",
  },
  // 1b. Chemistry Equation Question
  {
    id: "q-chem-1",
    subjectId: "sub-3",
    unitId: "unit-301",
    lessonId: "les-301-1",
    type: "mcq",
    text: "ما هي المعاملات الموزونة الصحيحة لتفاعل احتراق الميثان التالي: $a CH_4 + b O_2 \\longrightarrow c CO_2 + d H_2O$؟",
    answer: "$a=1, b=2, c=1, d=2$",
    difficulty: "medium",
    importance: 5,
    tags: ["موازنة معادلة", "كيمياء حرارية"],
    isPastCycle: true,
    pastCyclesInfo: "دورة 2024 - وزارية",
    occurrencesCount: 2,
    futureProbability: 90,
    lastUsedDate: "2025-05-10",
    finalWeightScore: 4.7,
    distractors: [
      { id: "cd1", text: "$a=1, b=1, c=1, d=1$", isCorrect: false },
      { id: "cd2", text: "$a=1, b=2, c=1, d=2$", isCorrect: true },
      { id: "cd3", text: "$a=2, b=1, c=2, d=1$", isCorrect: false },
      { id: "cd4", text: "$a=1, b=3, c=2, d=2$", isCorrect: false },
    ],
    createdAt: "2025-01-11",
  },
  // 1c. Chemistry Acids & Bases Questions
  {
    id: "q-chem-acids-1",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-1",
    type: "mcq",
    text: "حسب نظرية برونستد-لوري، ما هو الحمض المرافق للأساس $NH_3$ عند تفاعله مع الماء وفق التفاعل: $NH_3 + H_2O \\rightleftharpoons NH_4^+ + OH^-$؟",
    answer: "$NH_4^+$",
    difficulty: "easy",
    importance: 5,
    tags: ["حموض وأسس", "برونستد-لوري", "بكالوريا مهنية"],
    isPastCycle: true,
    pastCyclesInfo: "دورة 2024 - مهني",
    occurrencesCount: 3,
    futureProbability: 92,
    lastUsedDate: "2025-06-10",
    finalWeightScore: 4.8,
    distractors: [
      { id: "d-c1", text: "$OH^-$", isCorrect: false },
      { id: "d-c2", text: "$NH_4^+$", isCorrect: true },
      { id: "d-c3", text: "$NH_2^-$", isCorrect: false },
      { id: "d-c4", text: "$H_3O^+$", isCorrect: false },
    ],
    createdAt: "2025-01-15",
  },
  {
    id: "q-chem-acids-2",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-4",
    type: "problem",
    text: "محلول مائي لحمض الهيدروكلوريك $HCl$ تركيزه $10^{-2} \\text{ mol/L}$. احسب قيمة الأس الهيدروجيني $pH$ وقيمة $pOH$ لهذا المحلول.",
    answer:
      "حمض قوي يتأين كلياً: $[H_3O^+] = 10^{-2} \\text{ M} \\Rightarrow pH = -\\log(10^{-2}) = 2$. بما أن $pH + pOH = 14$ فإن $pOH = 14 - 2 = 12$.",
    difficulty: "medium",
    importance: 5,
    tags: ["حسابات pH", "حموض قوية", "مسألة هامة"],
    isPastCycle: true,
    pastCyclesInfo: "دورة 2023 - مهني وزارية",
    occurrencesCount: 5,
    futureProbability: 95,
    lastUsedDate: "2025-06-20",
    finalWeightScore: 4.9,
    createdAt: "2025-01-16",
  },
  {
    id: "q-chem-acids-3",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-7",
    type: "problem",
    text: "عُاير $20 \\text{ mL}$ من محلول هيدروكسيد الصوديوم $NaOH$ مجهول التركيز بمحلول حمض الهيدروكلوريك $HCl$ بتركيز $0.1 \\text{ mol/L}$، فاستُهلك $10 \\text{ mL}$ من الحمض عند نقطة التكافؤ. احسب تركيز الأساس بالمول/لتر.",
    answer:
      "معادلة المعايرة: $HCl + NaOH \\longrightarrow NaCl + H_2O$. عند التكافؤ $C_A V_A = C_B V_B \\Rightarrow 0.1 \\times 10 = C_B \\times 20 \\Rightarrow C_B = \\frac{1}{20} = 0.05 \\text{ mol/L}$.",
    difficulty: "hard",
    importance: 5,
    tags: ["معايرة حجمية", "تفاعل تعادل", "مسألة امتحانية"],
    isPastCycle: true,
    pastCyclesInfo: "دورة 2024 - الدورة الأولى",
    occurrencesCount: 4,
    futureProbability: 96,
    lastUsedDate: "2025-06-25",
    finalWeightScore: 5.0,
    createdAt: "2025-01-18",
  },
  // Lesson 1 additional questions
  {
    id: "q-chem-acids-4",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-1",
    type: "mcq",
    text: "أيّ من المركبات الآتية يُعتبر حمض لويس (Lewis Acid) لأنه يستقبل زوجاً من الإلكترونات غير الرابطة؟",
    answer: "$BF_3$",
    difficulty: "medium",
    importance: 5,
    tags: ["حموض وأسس", "نظرية لويس"],
    isPastCycle: true,
    pastCyclesInfo: "دورة 2024 - مهني",
    occurrencesCount: 2,
    futureProbability: 88,
    finalWeightScore: 4.5,
    distractors: [
      { id: "d-ca4-1", text: "$BF_3$", isCorrect: true },
      { id: "d-ca4-2", text: "$NH_3$", isCorrect: false },
      { id: "d-ca4-3", text: "$OH^-$", isCorrect: false },
      { id: "d-ca4-4", text: "$H_2O$", isCorrect: false },
    ],
    createdAt: "2025-01-19",
  },
  {
    id: "q-chem-acids-5",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-1",
    type: "true_false",
    text: "حسب نظرية برونستد-لوري، يعتبر الأساس هو أي مادة كيميائية قادرة على منح بروتون $H^+$ لمادة أخرى.",
    answer: "خطأ (الأساس يستقبل بروتون والبروتون الممنوح هو صفة الحمض)",
    difficulty: "easy",
    importance: 4,
    tags: ["حموض وأسس", "برونستد-لوري"],
    isPastCycle: false,
    occurrencesCount: 0,
    futureProbability: 80,
    finalWeightScore: 4.0,
    distractors: [
      { id: "d-ca5-1", text: "صح", isCorrect: false },
      { id: "d-ca5-2", text: "خطأ", isCorrect: true },
    ],
    createdAt: "2025-01-19",
  },
  {
    id: "q-chem-acids-6",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-1",
    type: "definition",
    text: "عرّف حمض برونستد-لوري وأساس برونستد-لوري مع كتابة صيغة الزوج المترافق (حمض/أساس).",
    answer:
      "حمض برونستد-لوري: مادة مانحة للبروتون $H^+$. أساس برونستد-لوري: مادة مستقبلة للبروتون $H^+$. الزوج المترافق يتكون من مادتين تختلفان ببروتون واحد مثل ($CH_3COOH / CH_3COO^-$).",
    difficulty: "medium",
    importance: 5,
    tags: ["تعاريف", "أزواج مترافقة"],
    isPastCycle: true,
    occurrencesCount: 3,
    futureProbability: 90,
    finalWeightScore: 4.7,
    createdAt: "2025-01-20",
  },
  {
    id: "q-chem-acids-7",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-1",
    type: "reason",
    text: "علّل: يُعتبر غاز النشادر $NH_3$ أساساً حسب نظرية لويس رغم عدم احتوائه على مجموعات هيدروكسيد $OH^-$.",
    answer:
      "لأن ذرة النيتروجين في جزيء النشادر تمتلك زوجاً إلكترونياً حراً غير رابط، وتستطيع منحه لاستقبال بروتون وتكوين رابطة تساندية.",
    difficulty: "medium",
    importance: 5,
    tags: ["تعليل", "نظرية لويس"],
    isPastCycle: true,
    occurrencesCount: 2,
    futureProbability: 85,
    finalWeightScore: 4.3,
    createdAt: "2025-01-20",
  },
  {
    id: "q-chem-acids-8",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-1",
    type: "essay",
    text: "ارسم جدولاً يقارن بين نظريات الحموض والأسس الثلاث (أرهينيوس، برونستد-لوري، ولويس) من حيث مفهوم الحمض، مفهوم الأساس، وحدود شروط التطبيق.",
    answer:
      "أرهينيوس: حمض يحرر $H^+$ بمحلول مائي، أساس يحرر $OH^-$. برونستد: حمض يمنح $H^+$، أساس يستقبل $H^+$. لويس: حمض يستقبل زوج إلكتروني، أساس يمنح زوج إلكتروني.",
    difficulty: "hard",
    importance: 5,
    tags: ["مقارنة نظريات", "أسئلة مقالية"],
    isPastCycle: false,
    occurrencesCount: 1,
    futureProbability: 82,
    finalWeightScore: 4.2,
    createdAt: "2025-01-21",
  },
  {
    id: "q-chem-acids-9",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-1",
    type: "fill_blanks",
    text: "في التفاعل: $HNO_2 + H_2O \\rightleftharpoons NO_2^- + H_3O^+$، تسلك المادة $HNO_2$ سلوك .......... والمادة $H_2O$ سلوك ..........، والاساس المرافق لـ $HNO_2$ هو ..........",
    answer: "حمض | أساس | $NO_2^-$",
    difficulty: "medium",
    importance: 4,
    tags: ["أكمل الفراغات", "حموض وأسس"],
    isPastCycle: false,
    occurrencesCount: 0,
    futureProbability: 78,
    finalWeightScore: 3.9,
    createdAt: "2025-01-21",
  },

  // Lesson 2: Ka and Kb
  {
    id: "q-chem-acids-10",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-2",
    type: "mcq",
    text: "كلما زادت قيمة ثابت تأين الحمض $K_a$ عند درجة حرارة ثابتة، فإن ذلك يدل على:",
    answer: "زيادة قوة الحمض ودرجة تأينه وتركيز شوارد $H_3O^+$",
    difficulty: "medium",
    importance: 5,
    tags: ["ثوابت التأين", "قوة الحموض"],
    isPastCycle: true,
    occurrencesCount: 3,
    futureProbability: 92,
    finalWeightScore: 4.8,
    distractors: [
      {
        id: "d-ca10-1",
        text: "زيادة قوة الحمض ودرجة تأينه وتركيز شوارد $H_3O^+$",
        isCorrect: true,
      },
      { id: "d-ca10-2", text: "نقصان قوة الحمض وزيادة $pH$", isCorrect: false },
      { id: "d-ca10-3", text: "تحول الحمض إلى أساس قوي", isCorrect: false },
      { id: "d-ca10-4", text: "عدم تأين الحمض نهائياً", isCorrect: false },
    ],
    createdAt: "2025-01-22",
  },
  {
    id: "q-chem-acids-11",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-2",
    type: "true_false",
    text: "تتأين الحموض القوية مثل $HCl$ و $HNO_3$ تأيناً كلياً في المائي وتكون قيمة ثابت تفككها $K_a$ كبيرة جداً ويكون التفاعل غير عكسي.",
    answer: "صح",
    difficulty: "easy",
    importance: 4,
    tags: ["حموض قوية", "تأين تام"],
    isPastCycle: true,
    occurrencesCount: 2,
    futureProbability: 85,
    finalWeightScore: 4.3,
    distractors: [
      { id: "d-ca11-1", text: "صح", isCorrect: true },
      { id: "d-ca11-2", text: "خطأ", isCorrect: false },
    ],
    createdAt: "2025-01-22",
  },
  {
    id: "q-chem-acids-12",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-2",
    type: "definition",
    text: "عرّف ثابت تأين الحمض الضعيف $K_a$ واكتب عبارة الثابت لتفكك حمض الخل $CH_3COOH$ في الماء.",
    answer:
      "$K_a = \\frac{[CH_3COO^-][H_3O^+]}{[CH_3COOH]}$. وهو نسبة حاصل ضرب أسطار تراكيز الشوارد الناتجة إلى تركيز الحمض عند التوازن.",
    difficulty: "medium",
    importance: 5,
    tags: ["تعاريف", "عبارة Ka"],
    isPastCycle: true,
    occurrencesCount: 4,
    futureProbability: 91,
    finalWeightScore: 4.8,
    createdAt: "2025-01-23",
  },
  {
    id: "q-chem-acids-13",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-2",
    type: "reason",
    text: "علّل: لا تحسب قيمة ثابت التأين $K_a$ للحموض القوية جداً مثل حمض كلور الماء $HCl$ في المحاليل المائية.",
    answer:
      "لأن تأينها في الماء كلي ويكون تركيز جزيئات الحمض غير المتأينة في المقام صغيراً جداً يؤول للصفر فيكون الثابت صغيراً جداً أو غير محدد ($K_a \\to \\infty$).",
    difficulty: "medium",
    importance: 4,
    tags: ["تعليل", "ثوابت التأين"],
    isPastCycle: false,
    occurrencesCount: 1,
    futureProbability: 79,
    finalWeightScore: 4.0,
    createdAt: "2025-01-23",
  },
  {
    id: "q-chem-acids-14",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-2",
    type: "problem",
    text: "محلول مائي لحمض النمل $HCOOH$ تركيزه الابتدائي $C_0 = 0.1 \\text{ mol/L}$ وتأين منه $10^{-3} \\text{ mol/L}$ عند التوازن. احسب قيمة ثابت التأين $K_a$ ودرجة التأين $\\alpha$.",
    answer:
      "درجة التأين $\\alpha = \\frac{10^{-3}}{0.1} = 10^{-2} = 1\\%$. وثابت التأين $K_a = \\frac{[H_3O^+]^2}{C_0} = \\frac{(10^{-3})^2}{0.1} = 10^{-5}$.",
    difficulty: "hard",
    importance: 5,
    tags: ["مسألة Ka", "درجة التأين"],
    isPastCycle: true,
    occurrencesCount: 3,
    futureProbability: 93,
    finalWeightScore: 4.9,
    createdAt: "2025-01-24",
  },

  // Lesson 3: Kw
  {
    id: "q-chem-acids-15",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-3",
    type: "mcq",
    text: "تبلغ قيمة الجداء الأيوني للماء $K_w$ عند درجة حرارة $25^\\circ\\text{C}$:",
    answer: "$10^{-14}$",
    difficulty: "easy",
    importance: 5,
    tags: ["الجداء الأيوني للماء", "Kw"],
    isPastCycle: true,
    occurrencesCount: 5,
    futureProbability: 97,
    finalWeightScore: 5.0,
    distractors: [
      { id: "d-ca15-1", text: "$10^{-14}$", isCorrect: true },
      { id: "d-ca15-2", text: "$10^{-7}$", isCorrect: false },
      { id: "d-ca15-3", text: "$10^{-1}$", isCorrect: false },
      { id: "d-ca15-4", text: "$14$", isCorrect: false },
    ],
    createdAt: "2025-01-24",
  },
  {
    id: "q-chem-acids-16",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-3",
    type: "true_false",
    text: "في الماء النقي والمحاليل المتعادلة عند $25^\\circ\\text{C}$ يكون تركيز شوارد الهيدرونيوم $[H_3O^+]$ مساوياً لتركيز شوارد الهيدروكسيد $[OH^-] = 10^{-7} \\text{ mol/L}$.",
    answer: "صح",
    difficulty: "easy",
    importance: 4,
    tags: ["تأين الماء", "توازن مائي"],
    isPastCycle: true,
    occurrencesCount: 3,
    futureProbability: 88,
    finalWeightScore: 4.4,
    distractors: [
      { id: "d-ca16-1", text: "صح", isCorrect: true },
      { id: "d-ca16-2", text: "خطأ", isCorrect: false },
    ],
    createdAt: "2025-01-25",
  },
  {
    id: "q-chem-acids-17",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-3",
    type: "definition",
    text: "عرّف الجداء الأيوني للماء $K_w$ واكتب العبارة الرياضية التي تربط بين $[H_3O^+]$ و $[OH^-]$.",
    answer:
      "$K_w = [H_3O^+][OH^-] = 10^{-14}$ عند $25^\\circ\\text{C}$. وهو ثات ثابت يعبر عن حاصل ضرب تراكيز شوارد تأين الماء عند التوازن.",
    difficulty: "medium",
    importance: 5,
    tags: ["تعاريف", "Kw"],
    isPastCycle: true,
    occurrencesCount: 4,
    futureProbability: 92,
    finalWeightScore: 4.7,
    createdAt: "2025-01-25",
  },
  {
    id: "q-chem-acids-18",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-3",
    type: "reason",
    text: "علّل: يُعتبر الماء النقي موصلاً ضعيفاً جداً للتيار الكهربائي.",
    answer:
      "بسبب ظاهرة التأين الذاتي الضعيفة جداً للماء وفق التفاعل $2H_2O \\rightleftharpoons H_3O^+ + OH^-$ حيث ينشأ عدد ضئيل جداً من الشوارد الموصلة $[H_3O^+]=[OH^-]=10^{-7} \\text{ M}$.",
    difficulty: "medium",
    importance: 4,
    tags: ["تعليل", "ناقلية كهربائية"],
    isPastCycle: true,
    occurrencesCount: 2,
    futureProbability: 83,
    finalWeightScore: 4.2,
    createdAt: "2025-01-26",
  },
  {
    id: "q-chem-acids-19",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-3",
    type: "problem",
    text: "إذا كان تركيز شوارد الهيدرونيوم $[H_3O^+]$ في محلول مائي يساوي $2 \\times 10^{-4} \\text{ mol/L}$ عند $25^\\circ\\text{C}$، احسب تركيز شوارد الهيدروكسيد $[OH^-]$ وحدد صفة المحلول.",
    answer:
      "$[OH^-] = \\frac{K_w}{[H_3O^+]} = \\frac{10^{-14}}{2 \\times 10^{-4}} = 5 \\times 10^{-11} \\text{ mol/L}$. وبما أن $[H_3O^+] > [OH^-]$ فالمحلول حمضي.",
    difficulty: "medium",
    importance: 5,
    tags: ["حسابات Kw", "تراكيز مائية"],
    isPastCycle: true,
    occurrencesCount: 3,
    futureProbability: 90,
    finalWeightScore: 4.6,
    createdAt: "2025-01-26",
  },

  // Lesson 4: pH and pOH
  {
    id: "q-chem-acids-20",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-4",
    type: "mcq",
    text: "إذا كانت قيمة الأس الهيدروجيني لمحلول مائي $pH = 9$ عند درجة حرارة $25^\\circ\\text{C}$، فإن هذا المحلول يكون:",
    answer: "أساسياً (قاعدياً) وشوارد $OH^-$ أكثر من $H_3O^+$",
    difficulty: "easy",
    importance: 5,
    tags: ["سلم pH", "صفة المحلول"],
    isPastCycle: true,
    occurrencesCount: 4,
    futureProbability: 94,
    finalWeightScore: 4.8,
    distractors: [
      {
        id: "d-ca20-1",
        text: "أساسياً (قاعدياً) وشوارد $OH^-$ أكثر من $H_3O^+$",
        isCorrect: true,
      },
      { id: "d-ca20-2", text: "حمضياً قوياً", isCorrect: false },
      { id: "d-ca20-3", text: "متعادلاً تماماً", isCorrect: false },
      { id: "d-ca20-4", text: "خالياً من الشوارد المائية", isCorrect: false },
    ],
    createdAt: "2025-01-27",
  },
  {
    id: "q-chem-acids-21",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-4",
    type: "true_false",
    text: "تزداد حموضة المحلول المائي الممدد كلما ارتفعت قيمة الرقم الهيدروجيني $pH$.",
    answer: "خطأ (تزداد الحموضة كلما انخفضت قيمة pH برفع تركيز H3O+)",
    difficulty: "easy",
    importance: 4,
    tags: ["سلم pH", "صح وخطأ"],
    isPastCycle: true,
    occurrencesCount: 2,
    futureProbability: 82,
    finalWeightScore: 4.1,
    distractors: [
      { id: "d-ca21-1", text: "صح", isCorrect: false },
      { id: "d-ca21-2", text: "خطأ", isCorrect: true },
    ],
    createdAt: "2025-01-27",
  },
  {
    id: "q-chem-acids-22",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-4",
    type: "essay",
    text: "اشرح بالرموز والعلاقات الرياضية لماذا يكون مجموع $pH + pOH = 14$ دائماً لأي محلول مائي عند درجة حرارة $25^\\circ\\text{C}$.",
    answer:
      "نبدأ من العبارة $K_w = [H_3O^+][OH^-] = 10^{-14}$، بوضع اللوغاريتم السالب للطرفين: $-\\log(K_w) = -\\log[H_3O^+] - \\log[OH^-] \\Rightarrow pK_w = pH + pOH = 14$.",
    difficulty: "medium",
    importance: 5,
    tags: ["إثبات رياضي", "pH و pOH"],
    isPastCycle: true,
    occurrencesCount: 3,
    futureProbability: 89,
    finalWeightScore: 4.6,
    createdAt: "2025-01-28",
  },
  {
    id: "q-chem-acids-23",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-4",
    type: "reason",
    text: "علّل: عند تمديد محلول حمضي بالماء المقوّى تزداد قيمة $pH$ وتقترب من الرقم 7 دون أن تتجاوزه.",
    answer:
      "لأن إضافة الماء تقلل تركيز شوارد الهيدرونيوم $[H_3O^+]$ باللتر، وبما أن $pH = -\\log[H_3O^+]$، فإن انخفاض التركيز يرفع القيمة نحو نقطة التعادل 7.",
    difficulty: "medium",
    importance: 5,
    tags: ["تعليل", "تمديد المحاليل"],
    isPastCycle: true,
    occurrencesCount: 4,
    futureProbability: 92,
    finalWeightScore: 4.7,
    createdAt: "2025-01-28",
  },
  {
    id: "q-chem-acids-24",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-4",
    type: "fill_blanks",
    text: "إذا كان $[H_3O^+] = 10^{-3} \\text{ mol/L}$ في محلول مائي فإن قيمة $pH = ..........$ وقيمة $pOH = ..........$ ويكون المحلول ذو صفة ..........",
    answer: "3 | 11 | حمضية",
    difficulty: "easy",
    importance: 4,
    tags: ["أكمل الفراغات", "حسابات pH"],
    isPastCycle: false,
    occurrencesCount: 1,
    futureProbability: 80,
    finalWeightScore: 4.0,
    createdAt: "2025-01-28",
  },

  // Lesson 5: Hydrolysis of Salts
  {
    id: "q-chem-acids-25",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-5",
    type: "mcq",
    text: "المحلول المائي لملح كلوريد الأمونيوم $NH_4Cl$ المذاب في الماء يتصف بأنه:",
    answer: "حمضي ($pH < 7$) بسبب إماهة شاردة $NH_4^+$",
    difficulty: "medium",
    importance: 5,
    tags: ["إماهة الأملاح", "طبيعة المحاليل"],
    isPastCycle: true,
    occurrencesCount: 4,
    futureProbability: 95,
    finalWeightScore: 4.9,
    distractors: [
      {
        id: "d-ca25-1",
        text: "حمضي ($pH < 7$) بسبب إماهة شاردة $NH_4^+$",
        isCorrect: true,
      },
      { id: "d-ca25-2", text: "أساسي ($pH > 7$)", isCorrect: false },
      { id: "d-ca25-3", text: "متعادل تماماً ($pH = 7$)", isCorrect: false },
      { id: "d-ca25-4", text: "غير قابل للانحلال في الماء", isCorrect: false },
    ],
    createdAt: "2025-01-29",
  },
  {
    id: "q-chem-acids-26",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-5",
    type: "true_false",
    text: "الملح الناتج عن تفاعل حمض قوي مع أساس قوي مثل $NaCl$ يعطي عند إذابته بالماء محلوماً متعادلاً ($pH = 7$) لأن الشوارد الناتجة حادية الحيود لا تتفاعل مع الماء.",
    answer: "صح",
    difficulty: "easy",
    importance: 4,
    tags: ["أملاح متعادلة", "إماهة"],
    isPastCycle: true,
    occurrencesCount: 3,
    futureProbability: 86,
    finalWeightScore: 4.3,
    distractors: [
      { id: "d-ca26-1", text: "صح", isCorrect: true },
      { id: "d-ca26-2", text: "خطأ", isCorrect: false },
    ],
    createdAt: "2025-01-29",
  },
  {
    id: "q-chem-acids-27",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-5",
    type: "definition",
    text: "عرّف إماهة الملح (Hydrolysis) واشرح الفرق بين الملح المادّ للماء والملح الخامل مائياً.",
    answer:
      "إماهة الملح هي تفاعل إحدى شوارد الملح (الضعيفة) مع الماء لتكوين حمض ضعيف أو أساس ضعيف يغير قيمة pH المحلول.",
    difficulty: "medium",
    importance: 5,
    tags: ["تعاريف", "إماهة الأملاح"],
    isPastCycle: true,
    occurrencesCount: 3,
    futureProbability: 88,
    finalWeightScore: 4.5,
    createdAt: "2025-01-30",
  },
  {
    id: "q-chem-acids-28",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-5",
    type: "reason",
    text: "علّل: الصفة الأساسية لمحلول خلات الصوديوم $CH_3COONa$ المائي ($pH > 7$).",
    answer:
      "لأن الملح ينحل كلياً ويعطي شوارد الخلات $CH_3COO^-$ التي تُماه بتفاعلها مع الماء لتأخذ $H^+$ وتنتج شوارد $OH^-$ حرة ترتفع بها القيمة $pH > 7$.",
    difficulty: "medium",
    importance: 5,
    tags: ["تعليل", "إماهة خلات الصوديوم"],
    isPastCycle: true,
    occurrencesCount: 4,
    futureProbability: 93,
    finalWeightScore: 4.8,
    createdAt: "2025-01-30",
  },
  {
    id: "q-chem-acids-29",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-5",
    type: "equation",
    text: "اكتب معادلتي إماهة الملحين التاليين بالماء وحدد طبيعة كل محلول: 1) كلوريد الأمونيوم $NH_4Cl$. 2) خلات الصوديوم $CH_3COONa$.",
    answer:
      "1) $NH_4^+ + H_2O \\rightleftharpoons NH_3 + H_3O^+$ (حمضي $pH<7$). 2) $CH_3COO^- + H_2O \\rightleftharpoons CH_3COOH + OH^-$ (أساسي $pH>7$).",
    difficulty: "hard",
    importance: 5,
    tags: ["معادلات كيميائية", "إماهة"],
    isPastCycle: true,
    occurrencesCount: 3,
    futureProbability: 91,
    finalWeightScore: 4.7,
    createdAt: "2025-01-31",
  },

  // Lesson 6: Buffer Solutions
  {
    id: "q-chem-acids-30",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-6",
    type: "mcq",
    text: "يتكون المحلول المنظم (المحلول المصد / Buffer Solution) عادة من مخلوط يضم:",
    answer: "حمض ضعيف مع أحد أملاحه المشتقة من أساس قوي (أو أساس ضعيف وملحه)",
    difficulty: "medium",
    importance: 5,
    tags: ["محاليل منظمة", "تركيب البفر"],
    isPastCycle: true,
    occurrencesCount: 4,
    futureProbability: 96,
    finalWeightScore: 4.9,
    distractors: [
      {
        id: "d-ca30-1",
        text: "حمض ضعيف مع أحد أملاحه المشتقة من أساس قوي (أو أساس ضعيف وملحه)",
        isCorrect: true,
      },
      {
        id: "d-ca30-2",
        text: "حمض قوي جداً مع أساس قوي جداً",
        isCorrect: false,
      },
      {
        id: "d-ca30-3",
        text: "ماء مقطر مع ملح طعام متعادل فقط",
        isCorrect: false,
      },
      { id: "d-ca30-4", text: "حمض هيدروكلوريك مركز", isCorrect: false },
    ],
    createdAt: "2025-01-31",
  },
  {
    id: "q-chem-acids-31",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-6",
    type: "true_false",
    text: "المحلول المنظم هو المحلول الذي يقاوم التغيرات الكبيرة في الرقم الهيدروجيني $pH$ عند إضافة كميات ضئيلة من حمض قوي أو أساس قوي.",
    answer: "صح",
    difficulty: "easy",
    importance: 5,
    tags: ["محاليل منظمة", "خواص البفر"],
    isPastCycle: true,
    occurrencesCount: 3,
    futureProbability: 88,
    finalWeightScore: 4.4,
    distractors: [
      { id: "d-ca31-1", text: "صح", isCorrect: true },
      { id: "d-ca31-2", text: "خطأ", isCorrect: false },
    ],
    createdAt: "2025-02-01",
  },
  {
    id: "q-chem-acids-32",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-6",
    type: "definition",
    text: "عرّف المحلول المنظم (Buffer Solution) واذكر مثالاً حيوياً لاستخدامه في جسم الإنسان.",
    answer:
      "المحلول المنظم: محلول يقاوم التغير الحاد في pH عند إضافة حمض أو أساس قوي. أبراز مثال حيوي: بفر الكربونات والبيكربونات في دم الإنسان لتثبيت pH عند 7.4.",
    difficulty: "medium",
    importance: 5,
    tags: ["تعاريف", "محاليل منظمة"],
    isPastCycle: true,
    occurrencesCount: 4,
    futureProbability: 92,
    finalWeightScore: 4.7,
    createdAt: "2025-02-01",
  },
  {
    id: "q-chem-acids-33",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-6",
    type: "reason",
    text: "علّل: ثبات قيمة $pH$ لدم الإنسان عند القيمة القريبة من 7.4 رغم تناول حموض وقواعد مختلفة.",
    answer:
      "لوجود الجملة المنظمة الحيوية ($H_2CO_3 / HCO_3^-$) في بلازما الدم حيث تعادل الشوارد المضافة وتمنع حدوث تحمض أو تقلي الدم.",
    difficulty: "medium",
    importance: 5,
    tags: ["تعليل", "حيوية الدم"],
    isPastCycle: true,
    occurrencesCount: 3,
    futureProbability: 89,
    finalWeightScore: 4.5,
    createdAt: "2025-02-02",
  },
  {
    id: "q-chem-acids-34",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-6",
    type: "essay",
    text: "اشرح آلية عمل المحلول المنظم المكون من حمض الخل وخلات الصوديوم ($CH_3COOH / CH_3COONa$) عند إضافة كمية قليلة من حمض الهيدروكلوريك $HCl$.",
    answer:
      "عند إضافة $HCl$ المعتمد، تتحد شوارد $H_3O^+$ المضافة مع شوارد الخلات $CH_3COO^-$ المتوفرة بكثرة لتشكل حمض الخل الضعيف غير المتأين، فيقل استهلاك $H_3O^+$ الحرة ويحافظ المحلول على $pH$.",
    difficulty: "hard",
    importance: 4,
    tags: ["آلية عمل البفر", "أسئلة إنشائية"],
    isPastCycle: false,
    occurrencesCount: 1,
    futureProbability: 81,
    finalWeightScore: 4.1,
    createdAt: "2025-02-02",
  },

  // Lesson 7: Titration and Equivalence
  {
    id: "q-chem-acids-35",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-7",
    type: "mcq",
    text: "عند نقطة التكافؤ في معايرة حمض ضعيف (مثل $CH_3COOH$) بأساس قوي (مثل $NaOH$)، يكون المشعر الملائم لتحديد نقطة النهاية هو:",
    answer: "الفينول فثالئين (لانتقاله في المجال الأساسي $pH = 8.2 - 10$)",
    difficulty: "medium",
    importance: 5,
    tags: ["معايرة", "المشعرات الملونة"],
    isPastCycle: true,
    occurrencesCount: 4,
    futureProbability: 95,
    finalWeightScore: 4.9,
    distractors: [
      {
        id: "d-ca35-1",
        text: "الفينول فثالئين (لانتقاله في المجال الأساسي $pH = 8.2 - 10$)",
        isCorrect: true,
      },
      { id: "d-ca35-2", text: "الهليانتين (أورانج الميثيل)", isCorrect: false },
      { id: "d-ca35-3", text: "ورق عباد الشمس الأحمر فقط", isCorrect: false },
      { id: "d-ca35-4", text: "حمض الكبريتيك", isCorrect: false },
    ],
    createdAt: "2025-02-03",
  },
  {
    id: "q-chem-acids-36",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-7",
    type: "true_false",
    text: "عند نقطة التكافؤ في المعايرة الحجمية، يكون عدد مولات شوارد $H_3O^+$ المضافة من الحمض مساوياً لعدد مولات شوارد $OH^-$ في الأساس المعاير.",
    answer: "صح",
    difficulty: "easy",
    importance: 5,
    tags: ["نقطة التكافؤ", "معايرة"],
    isPastCycle: true,
    occurrencesCount: 4,
    futureProbability: 92,
    finalWeightScore: 4.7,
    distractors: [
      { id: "d-ca36-1", text: "صح", isCorrect: true },
      { id: "d-ca36-2", text: "خطأ", isCorrect: false },
    ],
    createdAt: "2025-02-03",
  },
  {
    id: "q-chem-acids-37",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-7",
    type: "definition",
    text: "عرّف كلاً من: 1) نقطة التكافؤ النظرية (Equivalence Point). 2) نقطة نهاية المعايرة التجريبية (End Point).",
    answer:
      "1) نقطة التكافؤ النظرية: النقطة التي تتكافؤ عندها كيمائياً كمية الحمض مع كمية الأساس. 2) نقطة نهاية المعايرة: النقطة التي يتغير عندها لون المشعر الملون المضاف وتوقف المعايرة.",
    difficulty: "medium",
    importance: 5,
    tags: ["تعاريف", "معايرة"],
    isPastCycle: true,
    occurrencesCount: 5,
    futureProbability: 96,
    finalWeightScore: 4.9,
    createdAt: "2025-02-04",
  },
  {
    id: "q-chem-acids-38",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-7",
    type: "matching",
    text: "صل كل نوع من أنواع المعايرة بالمشعر الملون الأكثر ملاءمة لها في التجربة:",
    answer:
      "حمض قوي + أساس قوي -> أزرق البروموثيمول | حمض ضعيف + أساس قوي -> الفينول فثالئين | حمض قوي + أساس ضعيف -> أورانج الميثيل (الهليانتين)",
    difficulty: "medium",
    importance: 4,
    tags: ["توصيل", "معايرة ومشعرات"],
    isPastCycle: true,
    occurrencesCount: 2,
    futureProbability: 84,
    matchingPairs: [
      {
        left: "حمض قوي مع أساس قوي",
        right: "أزرق البروموثيمول ($pH \\approx 7$)",
      },
      { left: "حمض ضعيف مع أساس قوي", right: "الفينول فثالئين ($pH > 7$)" },
      {
        left: "حمض قوي مع أساس ضعيف",
        right: "الهليانتين / أحمر الميثيل ($pH < 7$)",
      },
    ],
    finalWeightScore: 4.3,
    createdAt: "2025-02-04",
  },

  // Lesson 8: Applications & Problems
  {
    id: "q-chem-acids-39",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-8",
    type: "mcq",
    text: "تُستخدم الحموض والقواعد القوية في التطبيقات الصناعية والمهنية بشكل واسع، ومنها استخدام حمض الكبريتيك $H_2SO_4$ الرئيسي في:",
    answer: "تصنيع بطاريات ومداخر السيارات الرصاصية والأسمدة الكيميائية",
    difficulty: "easy",
    importance: 4,
    tags: ["تطبيقات مهنية", "استخدامات الحموض"],
    isPastCycle: true,
    occurrencesCount: 3,
    futureProbability: 85,
    finalWeightScore: 4.2,
    distractors: [
      {
        id: "d-ca39-1",
        text: "تصنيع بطاريات ومداخر السيارات الرصاصية والأسمدة الكيميائية",
        isCorrect: true,
      },
      {
        id: "d-ca39-2",
        text: "حفظ المأكولات والمشروبات الغازية فقط",
        isCorrect: false,
      },
      { id: "d-ca39-3", text: "تحضير معجون الأسنان", isCorrect: false },
      {
        id: "d-ca39-4",
        text: "إنتاج غاز الأوكسجين النقي للطبابة",
        isCorrect: false,
      },
    ],
    createdAt: "2025-02-05",
  },
  {
    id: "q-chem-acids-40",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-8",
    type: "true_false",
    text: "عند انسكاب كمية من حمض قوي في ورشة الكيمياء الصناعية، يجب غسل المكان فوراً بماء غزير ثم معادلته بمادة أساسية ضئيلة الضرر مثل بيكربونات الصوديوم.",
    answer: "صح",
    difficulty: "easy",
    importance: 4,
    tags: ["سلامة مهنية", "ورش مهنية"],
    isPastCycle: true,
    occurrencesCount: 2,
    futureProbability: 88,
    finalWeightScore: 4.4,
    distractors: [
      { id: "d-ca40-1", text: "صح", isCorrect: true },
      { id: "d-ca40-2", text: "خطأ", isCorrect: false },
    ],
    createdAt: "2025-02-05",
  },
  {
    id: "q-chem-acids-41",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-8",
    type: "problem",
    text: "مسألة شاملة تطبيقية: أُذيب $4 \\text{ g}$ من هيدروكسيد الصوديوم النقي $NaOH$ في ماء مقطر للحصول على محلول حجمه $500 \\text{ mL}$. (الكتلة المولية $M(NaOH) = 40 \\text{ g/mol}$).\n1. احسب التركيز المولي للمحلول الناتج.\n2. احسب قيمة $pH$ هذا المحلول عند $25^\\circ\\text{C}$.\n3. احسب حجم محلول حمض $HCl$ تركيزه $0.1 \\text{ mol/L}$ اللازم لمعادلة $100 \\text{ mL}$ من محلول الأساس السابق.",
    answer:
      "1. عدد المولات $n = \\frac{m}{M} = \\frac{4}{40} = 0.1 \\text{ mol}$. التركيز $C = \\frac{n}{V} = \\frac{0.1}{0.5} = 0.2 \\text{ mol/L}$.\n2. $[OH^-] = 0.2 \\text{ M} \\Rightarrow pOH = -\\log(0.2) = 0.7 \\Rightarrow pH = 14 - 0.7 = 13.3$.\n3. المعادلة $C_A V_A = C_B V_B \\Rightarrow 0.1 \\times V_A = 0.2 \\times 100 \\Rightarrow V_A = 200 \\text{ mL}$.",
    difficulty: "hard",
    importance: 5,
    tags: ["مسألة شاملة", "تركيز وpH ومعايرة"],
    isPastCycle: true,
    pastCyclesInfo: "دورة 2024 - الامتحان الوزاري المهني النهائي",
    occurrencesCount: 5,
    futureProbability: 98,
    finalWeightScore: 5.0,
    createdAt: "2025-02-06",
  },
  {
    id: "q-chem-acids-42",
    subjectId: "sub-5",
    unitId: "unit-302",
    lessonId: "les-chem-8",
    type: "essay",
    text: "اكتب تقريراً فنياً موجزاً يعرض قواعد وإرشادات السلامة والوقاية المهنية الواجب اتباعها في المختبرات والورش عند نقل وتداول واستخدام الحموض والقواعد المركزة.",
    answer:
      "تضمن التقارير: ارتداء النظارات والقفازات الواقية، سكب الحمض فوق الماء وليس العكس لتجنب الغليان المفاجئ، التهوئة المباشرة، وحفظ المواد في مستودعات مخصصة ومصنفة.",
    difficulty: "medium",
    importance: 4,
    tags: ["تقرير فني", "سلامة مهنية"],
    isPastCycle: false,
    occurrencesCount: 1,
    futureProbability: 82,
    finalWeightScore: 4.1,
    createdAt: "2025-02-06",
  },
  {
    id: "q-math-1",
    subjectId: "sub-1",
    unitId: "unit-101",
    lessonId: "les-101-1",
    type: "problem",
    text: "احسب قيمة التكامل المحدد التالي: $$\\int_{0}^{2} (3x^2 + 2x - 1) dx$$",
    answer:
      "$$\\int_{0}^{2} (3x^2 + 2x - 1) dx = [x^3 + x^2 - x]_{0}^{2} = (8 + 4 - 2) - 0 = 10$$",
    difficulty: "hard",
    importance: 5,
    tags: ["تكامل محدد", "تفاضل وتكامل"],
    isPastCycle: true,
    pastCyclesInfo: "دورة 2024 - الاستدراكية",
    occurrencesCount: 4,
    futureProbability: 94,
    lastUsedDate: "2025-06-01",
    finalWeightScore: 4.9,
    createdAt: "2025-01-13",
  },
  // 2. True/False
  {
    id: "q-2",
    subjectId: "sub-1",
    unitId: "unit-101",
    lessonId: "les-101-1",
    type: "true_false",
    text: "يكون المماس موازياً لمحور السينات إذا كانت المشتقة الأولى مساوية للصفر $f'(x) = 0$.",
    answer: "صح",
    difficulty: "easy",
    importance: 4,
    tags: ["تفسير هندسي", "مماس"],
    isPastCycle: true,
    pastCyclesInfo: "دورة 2023 - الفصل الثاني",
    occurrencesCount: 2,
    futureProbability: 85,
    lastUsedDate: "2024-12-20",
    finalWeightScore: 4.2,
    distractors: [
      { id: "d1", text: "صح", isCorrect: true },
      { id: "d2", text: "خطأ (يكون موازياً لمحور الصادات)", isCorrect: false },
    ],
    createdAt: "2025-01-12",
  },
  // 3. Definition
  {
    id: "q-3",
    subjectId: "sub-2",
    unitId: "unit-201",
    lessonId: "les-201-1",
    type: "definition",
    text: "عرّف الشغل الفيزيائي (Work)، واذكر وحدته في النظام الدولي (SI).",
    answer:
      "الشغل هو القوة المؤثرة على جسم في إزاحته لمسافة باتجاه القوة (W = F . d . cosθ)، ووحته هي الجول (Joule).",
    difficulty: "medium",
    importance: 5,
    tags: ["تعاريف", "ميكانيكا", "وحدات"],
    isPastCycle: true,
    pastCyclesInfo: "دورة 2025 - الفصل الأول",
    occurrencesCount: 4,
    futureProbability: 95,
    lastUsedDate: "2025-01-20",
    finalWeightScore: 4.9,
    createdAt: "2025-01-15",
  },
  // 4. Reason (علّل)
  {
    id: "q-4",
    subjectId: "sub-2",
    unitId: "unit-201",
    lessonId: "les-201-1",
    type: "reason",
    text: "علّل: تتكسر البيضة عند سقوطها على أرضية خرسانية بينما لا تتكسر عند سقوطها من نفس الارتفاع على وسادة إسفنجية.",
    answer:
      "لأن الوسادة الإسفنجية تزيد من زمن زمن التأثير (Δt)، فيقل مقدار قوة الصدمة المؤثرة F = Δp / Δt وفق مبدأ الدفع والزخم.",
    difficulty: "hard",
    importance: 4,
    tags: ["تعليل", "الدفع والزخم"],
    isPastCycle: true,
    pastCyclesInfo: "دورة 2024 - الاستدراكية",
    occurrencesCount: 1,
    futureProbability: 78,
    lastUsedDate: "2024-08-10",
    finalWeightScore: 3.9,
    createdAt: "2025-01-18",
  },
  // 5. Problem
  {
    id: "q-5",
    subjectId: "sub-1",
    unitId: "unit-101",
    lessonId: "les-101-2",
    type: "problem",
    text: "مسألة: قطعة أرض مستطيلة الشكل يحدها نهر من أحد جوانبها. أوجد أبعاد قطعة الأرض التي تجعل مساحتها أكبر ما يمكن بشرط أن يكون طول السياج المحيط بالجوانب الثلاثة الأخرى يساوي 200 متر.",
    answer: "العرض x = 50m، الطول y = 100m، والمساحة القصوى = 5000 م².",
    difficulty: "hard",
    importance: 5,
    tags: ["تطبيقات عملية", "قيم قصوى"],
    isPastCycle: false,
    occurrencesCount: 0,
    futureProbability: 88,
    finalWeightScore: 4.5,
    createdAt: "2025-01-22",
  },
  // 6. Matching (توصيل)
  {
    id: "q-6",
    subjectId: "sub-4",
    unitId: "unit-401",
    lessonId: "les-401-1",
    type: "matching",
    text: "صل كل كلمة في العمود الأول بحالتها الإعرابية الصحيحة في العمود الثاني:",
    answer:
      "المبتدأ -> مرفوع وعلامة رفعه الضمة | مفعول لأجله -> منصوب وعلامة نصبه الفتحة | المضاف إليه -> مجرور وعلامة جره الكسرة",
    difficulty: "easy",
    importance: 3,
    tags: ["توصيل", "إعراب"],
    isPastCycle: false,
    occurrencesCount: 0,
    futureProbability: 70,
    matchingPairs: [
      { left: "المبتدأ والخبر", right: "مرفوع دائمًا" },
      { left: "المفعول به والمطلق", right: "منصوب دائمًا" },
      { left: "المضاف إليه بحرف الجر", right: "مجرور دائمًا" },
    ],
    finalWeightScore: 3.5,
    createdAt: "2025-01-25",
  },
  // 7. Chemical Equation (معادلة كيميائية)
  {
    id: "q-7",
    subjectId: "sub-3",
    unitId: "unit-301",
    lessonId: "les-301-1",
    type: "equation",
    text: "وازن المعادلة الكيميائية التالية وحدد نوع التفاعل:\nFe + O2 → Fe2O3",
    answer: "4Fe + 3O2 → 2Fe2O3 (تفاعل أكسدة/تكوين)",
    difficulty: "medium",
    importance: 4,
    tags: ["موازنة", "كيمياء"],
    isPastCycle: true,
    pastCyclesInfo: "دورة 2023 - الفصل الأول",
    occurrencesCount: 2,
    futureProbability: 82,
    finalWeightScore: 4.1,
    createdAt: "2025-01-26",
  },
  // 8. Grammar / Parsing (إعراب)
  {
    id: "q-8",
    subjectId: "sub-4",
    unitId: "unit-401",
    lessonId: "les-401-1",
    type: "grammar",
    text: "أعرب الكلمة المخطوط تحتها في الجملة التالية: «يَجْتَهِدُ العُمّالُ كَيْ يُحَقِّقُوا النَّجاحَ».",
    answer:
      "يُحَقِّقُوا: فعل مضارع منصوب بـ (كي) وعلامة نصبه حذف النون لأنه من الأفعال الخمسة، وواو الجماعة ضمير متصل مبني في محل رفع فاعل.",
    difficulty: "medium",
    importance: 5,
    tags: ["إعراب", "الأفعال الخمسة"],
    isPastCycle: true,
    pastCyclesInfo: "دورة 2025 - الفصل الأول",
    occurrencesCount: 3,
    futureProbability: 90,
    finalWeightScore: 4.7,
    createdAt: "2025-01-27",
  },
];

export const initialPrintTemplates: PrintTemplate[] = [
  {
    id: "tmpl-1",
    name: "القالب المالي والتعليمي الرسمي A4 (رأسي)",
    type: "lesson",
    orientation: "portrait",
    marginsCm: { top: 2.0, bottom: 2.0, left: 1.5, right: 1.5 },
    headerContent: {
      schoolName: "مدارس إديوتيك النموذجية الخاصة",
      logoUrl: "",
      showHijriDate: true,
      showGregorianDate: true,
      subjectName: "الماده: الرياضيات العامة",
      customText: "إعداد قسم المناهج والتحصيل الأكاديمي",
    },
    footerContent: {
      teacherName: "إعداد المدرس الأكاديمي المعتمد",
      showPageNumber: true,
      copyrightNotice:
        "جميع الحقوق محفوظة - نظام إديوتيك لإدارة المناهج © 2026",
    },
    isDefault: true,
  },
  {
    id: "tmpl-2",
    name: "قالب الامتحان النهائي المعتمد A4",
    type: "exam",
    orientation: "portrait",
    marginsCm: { top: 1.8, bottom: 1.8, left: 1.5, right: 1.5 },
    headerContent: {
      schoolName: "المثنى لطلاب الهندسة",
      showHijriDate: true,
      showGregorianDate: true,
      subjectName: "اختبار نهاية الفصل الدراسي الأول",
    },
    footerContent: {
      teacherName: "مع تمنياتنا بالتوفيق والنجاح",
      showPageNumber: true,
      copyrightNotice: "صفحة امتحانية رسمية - يمنع الاصطحاب إلى خارج القاعة",
    },
    isDefault: true,
  },
];

export const initialExamTemplates: ExamTemplate[] = [
  {
    id: "ex-tmpl-1",
    name: "قالب الورقة الامتحانية الرسمية (100 درجة)",
    subjectId: "sub-1",
    headerTitle: "امتحان الفصل الدراسي الأول النهائي",
    studentFields: {
      name: true,
      grade: true,
      section: true,
      studentId: true,
      date: true,
      timeAllowed: true,
    },
    showGradesTable: true,
    instructions: [
      "اقرأ الأسئلة بعناية قبل البدء بالإجابة.",
      "الزمن المخصص للامتحان: ساعتان ونصف.",
      "يمنع استخدام الآلة الحاسبة المبرمجة.",
      "تأكد من إجابة جميع الأسئلة في الأماكن المخصصة.",
    ],
    sections: [
      {
        id: "sec-1",
        title: "السؤال الأول: اختر الإجابة الصحيحة",
        questionType: "mcq",
        weightPercentage: 40,
      },
      {
        id: "sec-2",
        title: "السؤال الثاني: ضع علامة (صح) أو (خطأ)",
        questionType: "true_false",
        weightPercentage: 20,
      },
      {
        id: "sec-3",
        title: "السؤال الثالث: المسائل والتطبيقات العملية",
        questionType: "problem",
        weightPercentage: 40,
      },
    ],
  },
];

export const initialExams: Exam[] = [
  {
    id: "exam-001",
    title: "اختبار نهاية الفصل - الرياضيات العامة (نموذج أ)",
    subjectId: "sub-1",
    unitIds: ["unit-101", "unit-102"],
    lessonIds: ["les-101-1", "les-101-2"],
    totalQuestions: 5,
    totalMarks: 100,

    difficultyProfile: "balanced",
    generationType: "auto",
    createdAt: "2026-01-15",
    createdBy: "أ. محمد العلي (معلم المادة)",
    status: "finalized",
    pedagogicalRationale:
      "تم صياغة هذا الامتحان بواسطة خوارزمية إديوتيك الذكية لضمان تغطية 100% لمخرجات التعلم مع توزيع 40% للتطبيق المباشر، 40% للتحليل، و20% للمهارات العليا.",
    versions: [
      {
        versionCode: "أ",
        questions: [
          { id: "q-1", questionId: "q-1", allocatedMarks: 20, questionOrder: 1 },
          { id: "q-2", questionId: "q-2", allocatedMarks: 15, questionOrder: 2 },
          { id: "q-5", questionId: "q-5", allocatedMarks: 35, questionOrder: 3 },
          { id: "q-3", questionId: "q-3", allocatedMarks: 15, questionOrder: 4 },
          { id: "q-4", questionId: "q-4", allocatedMarks: 15, questionOrder: 5 },
        ],
      },
    ],
  },
];

export const initialCycles: Cycle[] = [
  {
    id: "cycle-2025-1",
    name: "الفصل الدراسي الأول 2025/2026",
    academicYear: "2025/2026",
    startDate: "2025-09-01",
    endDate: "2026-01-31",
    status: "active",

    examIds: ["exam-001"],
  },
  {
    id: "cycle-2024-2",
    name: "الفصل الدراسي الثاني 2024/2025",
    academicYear: "2024/2025",
    startDate: "2025-02-01",
    endDate: "2025-06-30",
    status: "archived",
    examIds: [],
  },
];

export const initialUsers: User[] = [
  {
    id: "usr-1",
    name: "أحمد محمود",
    username: "ahmed_admin",
    email: "admin@edutech.edu",
    role: "admin",
    allowedSubjectIds: ["sub-1", "sub-2", "sub-4", "sub-5", "sub-6"],
    status: "active",
    permissions: {
      curriculum: true,
      lessons: true,
      questions: true,
      exams: true,
      exports: true,
      reports: true,
      users: true,
      settings: true,
    },
  },
  {
    id: "usr-2",
    name: "د. خديجة الشامي",
    username: "khadija_sup",
    email: "supervisor@edutech.edu",
    role: "supervisor",
    allowedSubjectIds: ["sub-1", "sub-2"],
    status: "disabled",
    permissions: {
      curriculum: true,
      lessons: true,
      questions: true,
      exams: true,
      exports: false,
      reports: true,
      users: false,
      settings: false,
    },
  },
  {
    id: "usr-3",
    name: "أ. محمد العلي",
    username: "teacher_ali",
    email: "math.teacher@edutech.edu",
    role: "teacher",
    allowedSubjectIds: ["sub-1"],
    status: "disabled",
    permissions: {
      curriculum: false,
      lessons: true,
      questions: true,
      exams: true,
      exports: false,
      reports: false,
      users: false,
      settings: false,
    },
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: "log-101",
    userId: "usr-1",
    userName: "أ. أحمد محمود",
    userRole: "admin",
    action: "تفعيل النظام بالنسخة التجريبية الاحترافية",
    targetEntity: "الإعدادات والترخيص",
    entityType: "الإعدادات والترخيص",
    timestamp: "2026-07-26 10:00:00",
    result: "success",
    details: "تم التفعيل لـ 14 يوماً مع كامل صلاحيات محرك الذكاء الاصطناعي.",
  },
  {
    id: "log-102",
    userId: "usr-3",
    userName: "أ. محمد العلي",
    userRole: "teacher",
    action: "توليد امتحان تلقائي بالذكاء الاصطناعي",
    targetEntity: "الاختبارات",
    targetEntityId: "exam-001",
    entityType: "الاختبارات",
    entityId: "exam-001",
    timestamp: "2026-07-26 11:30:00",
    result: "success",
    details: "توليد النموذج 'أ' لمادة الرياضيات بإجمالي 100 درجة.",
  },
];

export const initialSettings: SystemSettings = {
  primaryColorHex: "#2563eb", // الأزرق (Blue)
  secondaryColorHex: "#059669", // الأخضر (Green)
  accentColorHex: "#dc2626", // الأحمر (Red)
  themeMode: "light",
  academyName: "المثنى لطلاب الهندسة",
  primaryContactNumber: "0945 997 570",
  additionalContactNumber: "0966 974 273",
  licenseKey: "EDU-2026-PRO-9842-X7",
  licenseStatus: "trial",
  trialDaysLeft: 14,
  autoBackupIntervalDays: 7,
  lastBackupDate: "2026-07-26",
};
